Memory pair game release
kottans/frontend-2021-homeworks pull request #113
Opened 2020-11-12 17:20 UTC by mustbefail

### Memory Pair Game

[Demo](https://mustbefail.github.io/memory-pair-game/) |
[Code base](https://github.com/mustbefail/memory-pair-game)

The code is submitted in a dedicated feature branch.
Please, review.

2020-11-16 09:49 UTC, AMashoshyna requested changes
Awesome job! Please see my comments below

2020-11-16 09:49 UTC, AMashoshyna commented on submissions/mustbefail/memory-pair-game/app.js
> +  card.classList.add('flip');
I have two problems with this function:  1) it is called `flipCard` and receives one card as an argument, but under the hood is affects all cards (by calling updateCardState) 2) iw does two separate things - flip one card and update all the others, while ideally a function should do only one thing.

I would try to remove `updateCardsState()` call from this function and give this responsibility to some other entity

2020-11-28 22:31 UTC, AMashoshyna commented
Hey @mustbefail ! Do you need any assistance from my side with this task?

2020-11-30 12:48 UTC, mustbefail commented
> Hey @mustbefail ! Do you need any assistance from my side with this task?

Hello. All clear. Postponed classes for a while. I got sick. I'm returning to duty.

2020-12-02 16:16 UTC, AMashoshyna commented
Get well soon!

2020-12-28 12:27 UTC, AMashoshyna approved these changes

2020-12-28 12:27 UTC, merged