html-css-popup review ZahumnyiAndrii
kottans/frontend-2021-homeworks pull request #116
Opened 2020-11-13 01:25 UTC by AndriiZahumnyi

### html-css-popup

[Demo] https://andriizahumnyi.github.io/HTML-CSS-practice-Hooli-style-Popup/ 
[Code base] https://github.com/AndriiZahumnyi/HTML-CSS-practice-Hooli-style-Popup

The code is submitted in a dedicated feature branch.
Please, review.

2020-11-13 11:58 UTC, smillims commented
Hey, good work! But I find some problems, let's correct it together!

2020-11-13 12:35 UTC, smillims requested changes
Against, here we are practice for [ally](https://medium.com/web-standards/pragmatic-a11y-rules-b16dd2f77685). Your popup-menu and button "More" don't work for using there just with keyboard help, if someone will be need to move in your web-site with keybord help (tab and space), so they couldn't do it.

2020-11-13 12:35 UTC, smillims commented on submissions/AndriiZahumnyi/html-css-popup/index.html
> +<html>
Add to `html` attribute `lang` to declare the language of this document.

2020-11-13 12:35 UTC, smillims commented on submissions/AndriiZahumnyi/html-css-popup/index.html
> +                  </div>
You can't add block tag `div` inside inline-element `a`.
If you want turn on focus on your page you should style this in your css file with help pseudo-class `:focus`.
I think that the last word in attribute `alt` isn't needed in this case. Just "Calendar" and in the feature cases the same example.

2020-11-13 12:35 UTC, smillims commented on submissions/AndriiZahumnyi/html-css-popup/index.html
> +                <a href="#">
Wrap your block .sub_container in `ul` | `ol` instead `div`, after this wrap your links in `li`.
We're practicing here for [ally](https://medium.com/web-standards/pragmatic-a11y-rules-b16dd2f77685), so don't forget about semantic.

2020-11-13 12:35 UTC, smillims commented on submissions/AndriiZahumnyi/html-css-popup/index.html
> +  <!-- <script src="" async defer></script> -->
Delete, please

2020-11-13 12:35 UTC, smillims commented on submissions/AndriiZahumnyi/html-css-popup/index.html
> +</html>
Here's add empty line

2020-11-13 12:35 UTC, smillims commented on submissions/AndriiZahumnyi/html-css-popup/main_style.css
> +}
Please, avoid styling by id.

2020-11-13 12:35 UTC, smillims commented on submissions/AndriiZahumnyi/html-css-popup/main_style.css
> +}
Don't forget about empty line

2020-11-13 12:35 UTC, smillims commented on submissions/AndriiZahumnyi/html-css-popup/main_style.css
> +  }
I recommend (when your `media` some bigger) add to another file and connect with help `link`

2020-11-13 12:35 UTC, smillims commented on submissions/AndriiZahumnyi/html-css-popup/index.html
> +                <hr />
I recommend use pseudo-element `:before` or `:after` if you want to add line, but in this case you are free in your choise

2020-11-13 12:35 UTC, smillims commented on submissions/AndriiZahumnyi/html-css-popup/index.html
> +              <input id="check02" type="checkbox" name="more_menu" />
Use class, not id

2020-11-13 12:35 UTC, smillims commented on submissions/AndriiZahumnyi/html-css-popup/index.html
> +          <li>Images</li>
"Mail" and "Images" must be links

2020-11-13 12:35 UTC, smillims commented on submissions/AndriiZahumnyi/html-css-popup/index.html
> +          <li><img class="kottans_png" src="/popup-icons/favicon.png" alt="favicon kottans"></li>
I think it's too should be links. Don't forget about `:focus`

2020-11-13 12:35 UTC, smillims commented on submissions/AndriiZahumnyi/html-css-popup/main_style.css
> +}
Add `cursor: poiner`

2020-11-13 12:49 UTC, AndriiZahumnyi commented
Hello!
Thanks a lot for review, for your time!
I`ll correct all these things soon and report.

2020-11-13 21:00 UTC, miroslav-kolomiets requested changes
Good job!
But I recommend you check your html code here https://validator.w3.org/nu/#textarea
you have many validation errors, please check it and fix it.

2020-11-14 18:38 UTC, AndriiZahumnyi commented
Hello, mentors!
I think, I`ve fixed all the problems, that I had in my practice project. Could you review again, please!

2020-11-14 18:40 UTC, smillims commented
> Hello, mentors!
> I think, I`ve fixed all the problems, that I had in my practice project. Could you review again, please!

Hey! I think you forget update your code base

2020-11-14 18:42 UTC, AndriiZahumnyi commented
> > Hello, mentors!
> > I think, I`ve fixed all the problems, that I had in my practice project. Could you review again, please!
> 
> Hey! I think you forget update your code base

100%!) sorry

2020-11-14 18:48 UTC, AndriiZahumnyi commented
> > Hello, mentors!
> > I think, I`ve fixed all the problems, that I had in my practice project. Could you review again, please!
> 
> Hey! I think you forget update your code base

Code base already updated!

2020-11-14 19:14 UTC, smillims commented
I like your new correct! Now wait for @miroslav-kolomiets

2020-11-14 19:18 UTC, AndriiZahumnyi commented
> I like your new correct! Now wait for @miroslav-kolomiets

OK! Thanks a lot!)

2020-11-16 20:46 UTC, miroslav-kolomiets approved these changes
Good job! Keep going!

2020-11-16 20:46 UTC, merged

2020-11-16 21:38 UTC, AndriiZahumnyi commented
> Good job! Keep going!

Thanks a lot!!