Practice
kottans/frontend-2021-homeworks pull request #122
Opened 2020-11-14 12:26 UTC by phpslonuk

# Hooli-style_Popup Done please confirm request

### task name

[Demo](link-to-webpage-on-github-pages) |
[Code base](link-to-complete-codebase-in-different-repo)

The code is submitted in a dedicated feature branch.
Please, review.

2020-11-14 13:06 UTC, miroslav-kolomiets requested changes
Nice job! But something can be improved.
Make menu items in one color and style please.
<img width="742" alt="Снимок экрана 2020-11-14 в 3 04 42 PM" src="https://user-images.githubusercontent.com/14906260/99147596-f0123700-268a-11eb-918a-183669410250.png">

2020-11-14 13:06 UTC, miroslav-kolomiets commented on submissions/phpslonuk/Popup/css/style.css
> +  border: 1px solid blue
```suggestion
  border-color: blue;
```

2020-11-14 13:06 UTC, miroslav-kolomiets commented on submissions/phpslonuk/Popup/css/style.css
> +  border: 1px solid gray
```suggestion
  border-color: gray;
```

2020-11-14 13:06 UTC, miroslav-kolomiets commented on submissions/phpslonuk/Popup/css/style.css
> +  color: black
Here (and in other places) add a semicolon `;`

2020-11-14 13:06 UTC, miroslav-kolomiets commented on submissions/phpslonuk/Popup/css/style.css
> +}
You have bug with item shifting on hover. You can fix it this way.
<img width="1366" alt="Снимок экрана 2020-11-14 в 2 58 37 PM" src="https://user-images.githubusercontent.com/14906260/99147534-8134de00-268a-11eb-8208-859e3b0e266d.png">

2020-11-14 13:06 UTC, miroslav-kolomiets commented on submissions/phpslonuk/Popup/css/style.css
> +}
Add new line in the end of the document.

2020-11-14 13:06 UTC, miroslav-kolomiets commented on submissions/phpslonuk/Popup/index.html
> +</html>
Add new line in the end of the document.

2020-11-14 16:38 UTC, phpslonuk commented
Fixed:
- ";" was adderd.
- added new line in the end of the document.
- top menu improved

2020-11-15 19:16 UTC, miroslav-kolomiets requested changes
Good job! But you forgot about "Make menu items in one color and style please." that I wrote in first comment.

2020-11-15 21:15 UTC, phpslonuk commented
please explain what you mean by one color and style?
![Menu](https://user-images.githubusercontent.com/37296610/99197020-5a64cd80-2798-11eb-848d-66f15b496d54.jpg)

2020-11-16 20:52 UTC, miroslav-kolomiets commented
> please explain what you mean by one color and style?
> ![Menu](https://user-images.githubusercontent.com/37296610/99197020-5a64cd80-2798-11eb-848d-66f15b496d54.jpg)

Yes, of course, please see the screen:
<img width="1373" alt="Снимок экрана 2020-11-16 в 10 48 16 PM" src="https://user-images.githubusercontent.com/14906260/99306788-54392480-285e-11eb-82bb-ef6e6c8da28c.png">

2020-11-16 20:56 UTC, miroslav-kolomiets commented
> please explain what you mean by one color and style?
> ![Menu](https://user-images.githubusercontent.com/37296610/99197020-5a64cd80-2798-11eb-848d-66f15b496d54.jpg)

Yes, of course, please see the screen:
<img width="1283" alt="Снимок экрана 2020-11-16 в 10 53 53 PM" src="https://user-images.githubusercontent.com/14906260/99307333-02dd6500-285f-11eb-83ae-09b88bc407ec.png">

2020-11-17 16:24 UTC, phpslonuk commented
I changed the color, added hover

2020-11-18 20:17 UTC, A-Ostrovnyy commented on submissions/phpslonuk/Popup/css/style.css
> +#trigger {
Watch the [video](https://www.youtube.com/watch?v=E6kLaaQFctU&t=413s) about hiding checkbox in the right way

2020-11-18 20:18 UTC, A-Ostrovnyy requested changes
Good work!

2020-11-19 17:28 UTC, phpslonuk commented
the checkbox was hidden, the right way

2020-11-19 17:56 UTC, A-Ostrovnyy commented on submissions/phpslonuk/Popup/css/style.css
> +  -moz-appearance: none;
For future situations after properties with vendor prefixes add the same property without vendor prefixes.)

2020-11-19 17:56 UTC, A-Ostrovnyy approved these changes
LGMT
Well done.

2020-11-24 09:05 UTC, closed without merging

2020-11-24 09:20 UTC, A-Ostrovnyy commented
@phpslonuk Why you close PR?

2020-11-25 08:08 UTC, suchov commented
probably some miss-understanding here, @phpslonuk pls open the PR one more time, all looks good to us.