Frogger
kottans/frontend-2021-homeworks pull request #127
Opened 2020-11-15 14:42 UTC by AnnaStoyano

### Frogger

[Demo](https://annastoyano.github.io/Frogger/index) |
[Code base](https://github.com/AnnaStoyano/Frogger)

Please, review.

2020-11-17 11:56 UTC, OleksiyRudenko commented
@AnnaStoyano looks nice! :)

While we're looking for some review capacity please feel free checking your code against the following list of requirements.

## Check-list

Minimal requirements to meet:
 * [ ] it is OK to employ ES6 features like `const`, `let` etc.
 * [ ] OO is implemented using JS prototype chain object model (**not** ES6 classes syntax)
 * Requirements re **Constants**:
   * [ ] all numbers like block dimensions, initial locations are defined as constants
   * [ ] there are core constants and derived constants
         (e.g. `const FIELD_WIDTH = BLOCK_WIDTH * BLOCKS_NUMBER;`)
   * [ ] arrays of constants are also constants 
         (e.g. `const INITIAL_POSITIONS = [1,2,3,4].map(rowNumber => rowNumber * BLOCK_HEIGHT);`)
   * [ ] const objects help organizing and structure const data even better
         (e.g. `const PLAYER_CONF = { initialPosition: {x: 1, y: 5}, sprite: '...', ...etc... };`
 * Requirements re **OOP**:
   * [ ] properties common for some classes are generalized into a base class
         (e.g. there is `Character` base class, which is extended by `Enemy` and `Player` classes)
   * [ ] class extension is implemented using `Subclass.prototype = Object.create(Superclass.prototype)`,
         not `Subclass.prototype = new Superclass(params);`;
         [Useful resource](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain)
   * [ ] classes do not refer to any global variables, like global variable `player`, which is an instance of `Player` class
         (referring to global constants and globals provided by the gaming platform like `Resources` is OK);
         Hint: pass `Player` instance as an argument to every enemy
   * [ ] Separation of Concerns principle is followed
         (e.g. `update` method does only rendering and 
         doesn't **contain** any inline code to check e.g. collisions)
   * [ ] the code is very [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

Please, confirm all items above are positive. Please, ask a question if anything above requires clarification.

2020-11-25 08:31 UTC, OleksiyRudenko requested changes
@AnnaStoyano thank you for the update.

The below comments comprise a partial review.

Please check your code against the checklist and:
> Please, confirm all items above are positive. Please, ask a question if anything above requires clarification.

2020-11-25 08:31 UTC, OleksiyRudenko commented on submissions/AnnaStoyano/frogger/app.js
> +    if (positionX - 50 < player.position.x && player.position.x < positionX + 50) {
Here `player` is a global variable.

From the checklist:
> classes do not refer to any global variables, like global variable player, which is an instance of Player class
(referring to global constants and globals provided by the gaming platform like Resources is OK);

Double check your entire code base to meet the requirement.

2020-11-25 08:31 UTC, OleksiyRudenko commented on submissions/AnnaStoyano/frogger/app.js
> +const enemy3 = new Enemy(0, 50, 20, 'images/enemy-bug.png', player);
200, 404, 7, 220 etc look look magic

From the requirements:
> all numbers like block dimensions, initial locations are defined as constants

2020-11-25 20:32 UTC, AnnaStoyano commented
@OleksiyRudenko  Thank you for your comments. I hope that I corrected my mistakes.

2020-11-30 19:26 UTC, OleksiyRudenko requested changes
@AnnaStoyano well done. Yet you will benefit more if you master data structures to save time and lines of code.

2020-11-30 19:26 UTC, OleksiyRudenko commented on submissions/AnnaStoyano/frogger/app.js
> +const allEnemies = [enemy1, enemy2, enemy3];
Whenever you feel adding an index in a variable name (like `ENEMY_1_SPEED`, `START_POSITION_ENEMY_3` or `enemy2`) this is clear sign that array would be more appropriate.
Imagine you'd be required to add values for dozens of characters.
There is also massive code repetition here (again, think of dozens of characters).
Can you devise an approach that would employ data structure (array of objects containing individual enemy settings)?
You might then efficiently use e.g. `Array.map`.

Hint:
`allEnemies = enemySettings.map(settings => new Enemy(settings.startPosition.X, settings.startPosition.Y, settings.speed, ENEMY_IMAGE, player))`

2020-11-30 22:03 UTC, AnnaStoyano commented
@OleksiyRudenko  Thank you for your advice and hint)

2020-12-06 07:03 UTC, OleksiyRudenko approved these changes
@AnnaStoyano well done!
There are still numbers with unclear semantic purpose worth being assigned in constant definitions.
At all times keep thinking of how your code **reads**. The closer to plain English the better.

2020-12-06 07:03 UTC, merged