JS DOM
kottans/frontend-2021-homeworks pull request #157
Opened 2020-11-22 18:39 UTC by ustymchyk

### JS DOM

[Demo](https://ustymchyk.github.io/js-dom/) |
[Code base](https://github.com/ustymchyk/ustymchyk.github.io/tree/master/js-dom)

The code is submitted in a dedicated feature branch.
Please, review.

2020-11-23 19:15 UTC, babayK0 requested changes
Good job :100: 

Lets do some improvements)

First of all, your code contains a lot of nested array operations. What should you do if count of elements will be hundreds of thousands ?
 
See my comments below and fix this one please`GET https://ustymchyk.github.io/favicon.ico 404`

2020-11-24 12:03 UTC, ustymchyk commented
@babayK0 

I rethought the implementation of this task.
Instead of creating elements, I`m generating DOMString.
Now code is much more readable and has less code.
Could you review it one more time, please?

2020-11-24 20:50 UTC, babayK0 requested changes
Wow, good rework !

But lets do one more step. 
What about changing your function declaration to function expressions ? With them your code will be more clean and readable)

2020-11-24 20:50 UTC, babayK0 commented on submissions/ustymchyk/js-dom/index.js
> +  document.querySelectorAll('.menu__item').forEach(btn => {
Maybe one event listener for wrapper will be better.

2020-11-25 07:41 UTC, ustymchyk commented
done
one more review, please) @babayK0

2020-11-25 07:42 UTC, babayK0 approved these changes
Good job :+1: 

P.S. My personal like for pokenons :smile_cat:

2020-11-25 07:42 UTC, merged