Add solution for #5 HTML & CSS Practice
kottans/frontend-2021-homeworks pull request #158
Opened 2020-11-22 19:51 UTC by Ant-C-tech

###HTML & CSS Practice

[Demo](https://ant-c-tech.github.io/-5-HTML-CSS-Practice/) |
[Code base](https://github.com/Ant-C-tech/-5-HTML-CSS-Practice)

The code is submitted in a dedicated feature branch.
Please, review.

2020-11-22 21:39 UTC, lenadgit reviewed
Really cool work! one of the best completing of this task

2020-11-22 21:39 UTC, lenadgit commented on submissions/Ant-C-tech/html-css-popup/index.html
> +</html>
could you please add an empty line at the end of the file?  If you see this symbol it means that an empty line is needed
![empty line](https://user-images.githubusercontent.com/10871447/99917473-39acf280-2d19-11eb-9090-c5d24be11a37.png)

2020-11-22 21:47 UTC, lenadgit requested changes

2020-11-22 21:47 UTC, lenadgit commented on submissions/Ant-C-tech/html-css-popup/index.html
> +</html>
could you please add an empty line at the end of the file?  If you see this symbol it means that an empty line is needed
![empty line](https://user-images.githubusercontent.com/10871447/99917473-39acf280-2d19-11eb-9090-c5d24be11a37.png)

2020-11-24 15:35 UTC, Ant-C-tech commented
Please, review my solution.

2020-11-24 22:26 UTC, lenadgit approved these changes

2020-11-24 22:26 UTC, merged

2020-11-25 07:45 UTC, Ant-C-tech commented
Thank you for merge and help with normalize css!