Dom api task
kottans/frontend-2021-homeworks pull request #169
Opened 2020-11-25 00:12 UTC by smillims

### JS-DOM

[Demo](https://smillims.github.io/dom/) |
[Code base](https://github.com/smillims/dom)

The code is submitted in a dedicated feature branch.
Please, review.

2020-11-25 09:08 UTC, babayK0 requested changes
Nice work, but let improve your code together.
First of all maybe change function declarations to function expressions. With them your code will be more structured and clean.

Also see my comments below.

2020-11-25 13:31 UTC, smillims commented on submissions/smillims/js-dom/script.js
> +	{	id: 3,
Hey, I'm not in all understand what you are meaning

2020-11-25 14:18 UTC, smillims commented on submissions/smillims/js-dom/script.js
> +	{	id: 3,
oh, maybe I have already understood ^^

2020-11-25 18:30 UTC, smillims commented on submissions/smillims/js-dom/script.js
> +	container.append(div);
I did in this way, but can't understand how to remove and add another `div` when i clicked on another item of my menu
```
const newDiv = document.createElement('div');
newDiv.classList.add('content-text');
newDiv.innerText = hero.description;
container.append(newDiv);
```

2020-11-28 20:50 UTC, closed without merging

2020-11-28 20:50 UTC, smillims commented
Deleted the local repo. Need to overwrite