Memory game
kottans/frontend-2021-homeworks pull request #195
Opened 2020-11-30 19:15 UTC by ustymchyk

_Complete the form below and remove this line._

### Memory – Pair Game

[Demo](https://ustymchyk.github.io/memory-game/) |
[Code base](https://github.com/ustymchyk/memory-game/tree/master)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-02 10:39 UTC, MaxKalashnyk requested changes
good job! Look at my comments below.
Special respect for Pokemons! 🥇

2020-12-02 10:39 UTC, MaxKalashnyk commented on submissions/ustymchyk/memory-pair-game/index.html
> +<script src="index.js"></script>
Move this `script` tag before the `body` tag closing

2020-12-02 10:39 UTC, MaxKalashnyk commented on submissions/ustymchyk/memory-pair-game/index.js
> +    addListeners() {
Use [event delegation](https://javascript.info/event-delegation), please. It'll help you to increase the performance of your app.

2020-12-02 10:39 UTC, MaxKalashnyk commented on submissions/ustymchyk/memory-pair-game/index.js
> +        if (this.openCards[0].getAttribute('data-id') === this.openCards[1].getAttribute('data-id')) {
you can use this.openCards[0].dataset.id here as well
Also, maybe using ternary operator will help to make this code shorter:
```suggestion
        this.openCards[0].dataset.id === this.openCards[1].dataset.id ?  this.addMatch() : this.closeCards()
```

2020-12-02 10:39 UTC, MaxKalashnyk commented on submissions/ustymchyk/memory-pair-game/index.js
> +                alert('Congratulations!');
It's better to move this congrats string to the constants.

2020-12-02 10:39 UTC, MaxKalashnyk commented on submissions/ustymchyk/memory-pair-game/index.js
> +        if (this.rightAnswers === 4) {
Create a constant for `4` value. Now it looks like a magic number

2020-12-02 10:39 UTC, MaxKalashnyk commented on submissions/ustymchyk/memory-pair-game/index.js
> +            }, 400);
It's better to move this value of `400` to the constants.

2020-12-02 10:39 UTC, MaxKalashnyk commented on submissions/ustymchyk/memory-pair-game/index.js
> +        }, 1000);
It's better to move this value of `1000` to the constants.

2020-12-02 10:39 UTC, MaxKalashnyk commented on submissions/ustymchyk/memory-pair-game/index.js
> +        }).join('');
👍🏻

2020-12-02 10:39 UTC, MaxKalashnyk commented on submissions/ustymchyk/memory-pair-game/index.js
> +        if (this.openCards.length < 2) {
Create a constant for `2` value. Now it looks like a magic number

2020-12-02 10:39 UTC, MaxKalashnyk commented on submissions/ustymchyk/memory-pair-game/index.css
> +body {
Now your game field has quite big height on my screen. I'd recommend you decreasing it and adjust to the screen height.
<img width="1432" alt="Screenshot 2020-12-02 at 12 29 01" src="https://user-images.githubusercontent.com/13544983/100862093-6391b200-349b-11eb-97ed-2b81870502a6.png">

2020-12-03 10:11 UTC, MaxKalashnyk requested changes
it looks much better. please look at my minor suggestion and we will ready to merge this PR

2020-12-03 14:38 UTC, ustymchyk commented
@MaxKalashnyk done

2020-12-03 14:42 UTC, MaxKalashnyk approved these changes
Good job! Approved!

2020-12-03 14:42 UTC, merged