OOP
kottans/frontend-2021-homeworks pull request #201
Opened 2020-12-02 19:44 UTC by natashafir

### Frogger game

[Demo](https://natashafir.github.io/frogger-game/) |
[Code base](https://github.com/natashafir/frogger-game/blob/main/js/app.js)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-05 20:14 UTC, OleksiyRudenko requested changes
@natashafir nice job!

It seems like bugs at their first appearance storm through the scene like jets! Not sure if it was intentional.

There are few flaws in the code to fix.

A checklist to your rescue.

 * [ ] it is OK to employ ES6 features like `const`, `let` etc.
 * [ ] the code is very [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)
 * [ ] OO is implemented using JS prototype chain object model (**not** ES6 classes syntax)
 * Requirements re **Constants**:
   * [ ] all numbers like block dimensions, initial locations are defined as named constants
         (e.g. `const STEP = 101;`) as otherwise numbers scattered across code base look cryptic;
         named constants add semantic meaning and improve readability
   * [ ] there are core constants and derived constants
         (e.g. derived constant `const FIELD_WIDTH = BLOCK_WIDTH * BLOCKS_NUMBER;`)
   * [ ] arrays of constants are also constants 
         (e.g. `const INITIAL_POSITIONS = [1,2,3,4].map(rowNumber => rowNumber * BLOCK_HEIGHT);`)
   * [ ] const objects help organizing and structure const data even better
         (e.g. `const PLAYER_CONF = { initialPosition: {x: 1, y: 5}, sprite: '...', ...etc... };`
 * Requirements re **OOP**:
   * [ ] classes do not refer to any global variables, like global variable `player`, which is an instance of `Player` class
         (referring to global constants and globals provided by the gaming platform like `Resources` is OK);
         Hint: pass `Player` instance as an argument to every enemy
   * [ ] Separation of Concerns principle is followed
         (e.g. `update` method does only rendering and doesn't contain any unrelated **inline** code;
         for example collision check is defined as a dedicated method and only called from inside `update`)
   * [ ] Nice To Have: properties common for some classes are generalized into a base class
         (e.g. there is `Character` base class, which is extended by `Enemy` and `Player` classes)
   * [ ] class extension is implemented using `Subclass.prototype = Object.create(Superclass.prototype)`,
         not `Subclass.prototype = new Superclass(params);`;
         [Useful resource](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain)
 * Most common mistakes
   * [ ] Make sure `target = condition ? valueWhenConditionTrue : valueWhenConditionFalse` is used instead of
         `condition ? target = valueWhenConditionTrue : target = valueWhenConditionFalse`;
         [Conditional (ternary) operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator)

Please, confirm all items above are positive. Please, ask a question if anything above requires clarification.

2020-12-06 14:19 UTC, natashafir commented
@OleksiyRudenko thank you a lot for the review, I will make an effort to improve my code.

2020-12-13 13:02 UTC, OleksiyRudenko requested changes
@natashafir a really good job!
A few fixes and we're done

2020-12-13 13:02 UTC, OleksiyRudenko commented on submissions/natashafir/oop/app.js
> +    let enemy = new Enemy(BUGS_START, bugY, 200);
There must be a semantic meaning behind mysterious number `200`. Tell a reader what it is without browsing the codebase.

2020-12-13 13:02 UTC, OleksiyRudenko commented on submissions/natashafir/oop/app.js
> +let bugLocation = [60, 145, 230];
Please demistify these numbers.
Can these be calculated from some basic values? Are these some pixel positions calculable from the game scene row number plus or minus certain offset?

2020-12-13 14:01 UTC, natashafir commented on submissions/natashafir/oop/app.js
> +    if (this.Collision()) player.resetPosition();
should be ```this.player.resetPosition()```?

2020-12-14 21:01 UTC, OleksiyRudenko approved these changes
@natashafir great job!

2020-12-14 21:01 UTC, merged