Initial commit
kottans/frontend-2021-homeworks pull request #204
Opened 2020-12-03 09:53 UTC by Jigsaff

### html-css-popup

[Demo](https://jigsaff.github.io/html-css-popup/) | [Code base](https://github.com/Jigsaff/html-css-popup/)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-03 19:51 UTC, lenadgit commented
Great job!  But if the user will use a Tab key for MENU navigation - open a popup will be impossible. Moving by Tab key - is a requirement for [a11y](https://developer.mozilla.org/en-US/docs/Web/Accessibility). Could you please fix it?

2020-12-03 20:06 UTC, lenadgit requested changes

2020-12-03 20:06 UTC, lenadgit commented on submissions/Jigsaff/html-css-popup/css/style.css
> +a:visited,
and the same for link (as on line 10)

2020-12-04 11:17 UTC, Jigsaff commented
Fixed, please review!

2020-12-04 23:10 UTC, lenadgit requested changes
When the user chooses the popup icon - the popup window should appear by clicking the Space key. Now there is not a possibility to open this popup by keyboard. Could you please fix it?

2020-12-08 11:19 UTC, Jigsaff commented
Fixed, please review!

2020-12-16 22:11 UTC, lenadgit approved these changes
Thank you for the submission. Feel free taking the next course module while you submission is being reviewed

2020-12-16 22:11 UTC, merged