Pokemons app
kottans/frontend-2021-homeworks pull request #208
Opened 2020-12-03 19:03 UTC by ustymchyk

### Friends App

[Demo](https://ustymchyk.github.io/app/) |
[Code base](https://github.com/ustymchyk/app)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-07 10:57 UTC, MaxKalashnyk requested changes
Awesome work! Appreciate your interesting architecture!
Look at my minor suggestions, please

2020-12-07 10:57 UTC, MaxKalashnyk commented on submissions/ustymchyk/friends-app/css/cards.css
> +.card {
I'd recommend you decreasing the size of the cards because now they look extremely big

2020-12-07 10:57 UTC, MaxKalashnyk commented on submissions/ustymchyk/friends-app/index.html
> +</html>
Add an empty line here, please

2020-12-07 10:57 UTC, MaxKalashnyk commented on submissions/ustymchyk/friends-app/js/sidebar-component.js
> +}
Add an empty line, please

2020-12-07 10:57 UTC, MaxKalashnyk commented on submissions/ustymchyk/friends-app/js/api.js
> +    const response = await fetch(this.aliases.list);
I'd recommend you adding `try-catch` for checking cases if it will be failed to get pokemons list

2020-12-07 10:57 UTC, MaxKalashnyk commented on submissions/ustymchyk/friends-app/js/cards-component.js
> +      if (type === "pokemons") {
I'd recommend to create a global const for the "pokemons" string

2020-12-07 10:57 UTC, MaxKalashnyk commented on submissions/ustymchyk/friends-app/js/index.js
> +  if (componentAlias === "cards") {
I'd recommend to create a global const for the "cards" and "sidebar" strings

2020-12-07 11:35 UTC, ustymchyk commented
@MaxKalashnyk, Thanks!
Everything done.

2020-12-08 08:30 UTC, MaxKalashnyk approved these changes
LGTM! Perfect work!

2020-12-08 08:30 UTC, merged