Dom api task
kottans/frontend-2021-homeworks pull request #210
Opened 2020-12-04 13:10 UTC by Ant-C-tech

### task_js_dom

[Demo](https://ant-c-tech.github.io/-7-Document-Object-Model-Practice/) |
[Code base](https://github.com/Ant-C-tech/-7-Document-Object-Model-Practice)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-04 15:24 UTC, babayK0 reviewed
Wow, such a beautiful work :heart_eyes:

Let improve your code together! 

Firstly, there are many comments that you do not need. Don't write comments for everything, especially on obvious things.  Clean and well-structured code is self-documented.

Secondly, when i click and content changes your `flexWrapper` shrinks. Maybe add  `min-height`  for this block ? ( or you can suggest other implementation)

When i click in `Ukraine` block multiple times it causes content changing. Add check for double click. 

Watch my comments below and let start first iteration of improving :wink:

2020-12-04 15:24 UTC, babayK0 commented on submissions/Ant-C-tech/dom-api-task/js/app.js
> +        iterator.addEventListener('click', function (event) {
I think one listener (for clicks) for `map` will be better.

2020-12-04 15:24 UTC, babayK0 commented on submissions/Ant-C-tech/dom-api-task/js/app.js
> +        iterator.addEventListener('click', function (event) {
you can use object destructuring 
```
({ target }) {
 ...
}
```

2020-12-04 15:24 UTC, babayK0 commented on submissions/Ant-C-tech/dom-api-task/js/app.js
> +    const target = getTargetId(event)
Change naming. This one is not target. It is ID.

You can get id with destructuring.

`const { id } = event.target`  or `const { id } = target` (if you can access `target` directly  )

2020-12-04 15:24 UTC, babayK0 commented on submissions/Ant-C-tech/dom-api-task/js/app.js
> +}
You dont need this function

2020-12-04 15:26 UTC, babayK0 requested changes

2020-12-04 15:26 UTC, babayK0 commented on submissions/Ant-C-tech/dom-api-task/js/app.js
> +    event.target.style.fill = '#00b0ff'
Use css

2020-12-05 11:42 UTC, Ant-C-tech commented
First, I want to say thank you for your review. It made me thought again about many aspects of my code. I formerly worked as an engineer and I good undestanding how it is boring to check students works. But for me I think it was the most important part of this course. Now I understand why nobody want to work with people without experience. You made greate job. 
I tried to made revisions step by step, commit by commit, but it is hard to me yet, because I planed my work bad.  
I found a problem in my app with fast changing of content, so it  made me changed the algoritm of changing content. I hope it will not make your work more difficult.
Regards.

2020-12-07 10:24 UTC, babayK0 requested changes

2020-12-07 10:24 UTC, babayK0 commented on submissions/Ant-C-tech/dom-api-task/js/app.js
> +        event.target.classList.toggle('land-active')
`classList.add` i think will be more understandable in this case. Do the same, but you don't need any `toggling` here. Previously you removed all active classes, so main feature of toggle will not used

2020-12-07 10:24 UTC, babayK0 commented on submissions/Ant-C-tech/dom-api-task/js/app.js
>  function showContent(param) {
change naming. `param` is not obvious. Maybe id will be better ?

2020-12-07 10:24 UTC, babayK0 commented on submissions/Ant-C-tech/dom-api-task/js/app.js
> +            contentSection.addEventListener('transitionend', function () {
Why here you have nested 'transitionend' listener ?

2020-12-07 10:27 UTC, babayK0 commented on submissions/Ant-C-tech/dom-api-task/js/app.js
> +    fragment.appendChild(imgBlock)
You can append many elements with one `append`

 [append](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append)

2020-12-07 10:29 UTC, babayK0 commented
@Ant-C-tech 

> First, I want to say thank you for your review. It made me thought again about many aspects of my code. I formerly worked as an engineer and I good undestanding how it is boring to check students works. But for me I think it was the most important part of this course. Now I understand why nobody want to work with people without experience. You made greate job.
> I tried to made revisions step by step, commit by commit, but it is hard to me yet, because I planed my work bad.
> I found a problem in my app with fast changing of content, so it made me changed the algoritm of changing content. I hope it will not make your work more difficult.
> Regards.

Thanks for your feedback :smile_cat:

2020-12-07 13:40 UTC, Ant-C-tech commented
Once again thank you for your review. Every time I read your notices I think how can I do not see these things. But I really can't yet. So it is very useful for me to work with your reviews.
With one review I did nothing so I want to explain my thoughts and maybe you can help me to make my code better.
It is about your review "Why here you have nested 'transitionend' listener ?". In this case I wanted to construct a chain of animation and events those have to occur consistently. First: turning off all click listeners, than  animation of hide content, than - change content outside the screen, than  - animation of showing content and than turning on all the click listeners. I guess I could make with function raf(fn) {
    window.requestAnimationFrame(function () {
        window.requestAnimationFrame(function () {
            fn()
        })
    })
} (it works not always properly - I think I do not understand it enough) or maybe promices (I do not understand them at all). So I could make my idea only with nested listeners.

2020-12-08 18:28 UTC, babayK0 commented
@Ant-C-tech 

> Once again thank you for your review. Every time I read your notices I think how can I do not see these things. But I really can't yet. 

Code review was invented to prevent "raw" on production. You cant to know everything. with help of other developers, resulting code on production will be improved, more clean, readable etc.

2020-12-08 23:12 UTC, babayK0 commented on submissions/Ant-C-tech/dom-api-task/js/app.js
> +    let subtitle = document.createElement('div')
Why not use const here ?

2020-12-09 12:53 UTC, Ant-C-tech commented
Thank you for you review. It is interesting, I have never heard about pointer-event. Now I have a bit different behave of hover but I think now it is more logical.

2020-12-11 13:08 UTC, babayK0 commented
Perfect job !!!

> One more I have noticed, there was one problem - when mousedown event happens on the one map area
> and mouseup event happens on the other map area
> application was crushed. I think, I fixed it but I am not sure that I did it in the right way.

It is not blocker i guess, so i can approve you pr now, but if you want we can debug this bug together.
Can you provide a 'broken' version in another branch? (don't open new pr, just send me link to branch with bug)

2020-12-11 13:08 UTC, babayK0 approved these changes

2020-12-11 13:08 UTC, merged