Task js oop
kottans/frontend-2021-homeworks pull request #215
Opened 2020-12-05 12:08 UTC by UA-girl

### JS OOP

[Demo](https://ua-girl.github.io/Frogger-game/) |
[Code base](https://github.com/UA-girl/Frogger-game)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-05 18:49 UTC, OleksiyRudenko commented
@UA-girl for the code review purposes we need `app.js` only. Please remove all other files and also make sure that no other files except `app.js` were changed. If they were then refactor your code so that only `app.js` contains any changes that were authored by you.

2020-12-06 07:38 UTC, OleksiyRudenko requested changes
@UA-girl a really good job!
However there is a violation of some of the OOP/SOLID principles. Please fix.

2020-12-06 07:38 UTC, OleksiyRudenko commented on submissions/UA-girl/task_js_oop/app.js
> +    allTreasures.forEach(treasure => treasure.checkCollisions(player));
Here player is onbiously a variable from outside the scope of this class.
In fact you do not need and in current scope you have a simple way to refer a player not resorting to any global variables.

`allEnemies` and `allTreasures` are also global variables. Please make the `Player` class receive them, not know them.

2020-12-06 09:45 UTC, UA-girl commented
I've tried to make fixes you mentioned ) Please, check my code. Hope I've done all right ))

2020-12-06 10:09 UTC, OleksiyRudenko approved these changes
@UA-girl well done!

2020-12-06 10:09 UTC, merged