Memory pair game
kottans/frontend-2021-homeworks pull request #227
Opened 2020-12-06 14:17 UTC by nadsatt

### Memory pair game

[Demo](https://nadsatt.github.io/kottans-homeworks/memory-pair-game/) |
[Code base](https://github.com/nadsatt/kottans-homeworks/tree/master/memory-pair-game)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-06 20:08 UTC, OleksiyRudenko commented
Please check your files and [this message](https://t.me/c/1382428271/27203) in students' chat.

2020-12-10 08:29 UTC, MaxKalashnyk requested changes
Awesome work!!! I really appreciate your creativity and so clean code. You rock!
Look at my minor suggestions, please

2020-12-10 08:29 UTC, MaxKalashnyk commented on submissions/nadsatt/memory-pair-game/index.js
> +const handleGameCardsGroupClick = function({target: {parentElement: {parentElement: el}}}){
I think you can simplify this function argument to the `target`. Now you strongly depend on your layout.
```suggestion
const handleGameCardsGroupClick = function({target}){
```

2020-12-10 08:29 UTC, MaxKalashnyk commented on submissions/nadsatt/memory-pair-game/index.js
> +    return openedGameCardsNumber === 2;
Move 2 to constants, please

2020-12-10 08:29 UTC, MaxKalashnyk commented on submissions/nadsatt/memory-pair-game/index.js
> +    card.classList.add('card--flipped');
You can move this class name string to constants. I met this class name quite often in your code. It would be easier to change it in one place.

2020-12-10 08:29 UTC, MaxKalashnyk commented on submissions/nadsatt/memory-pair-game/index.js
> +const sameGameCardsOpened = function(){
Start naming all of your functions from a verb, please

2020-12-10 08:29 UTC, MaxKalashnyk commented on submissions/nadsatt/memory-pair-game/index.js
> +const twoGameCardsOpened = function(){
Start naming all of your functions from a verb, please

2020-12-23 23:21 UTC, MaxKalashnyk commented on submissions/nadsatt/memory-pair-game/index.js
> +const doc = document.documentElement,
It's not a big blocker, but better to use appropriate const names.
JS has convention regarding global constants - NAMES_SHOULD_LOOK_LIKE_THIS

Please see examples https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const

2020-12-23 23:22 UTC, MaxKalashnyk approved these changes
Great job! We can approve this PR. Check my comment about the constants names, please

2020-12-23 23:22 UTC, merged