Frogger game
kottans/frontend-2021-homeworks pull request #249
Opened 2020-12-08 17:38 UTC by Ant-C-tech

### Frogger game

[Demo](https://ant-c-tech.github.io/frontend-nanodegree-arcade-game/)
[Code base](https://github.com/Ant-C-tech/frontend-nanodegree-arcade-game/tree/master/js)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-08 17:50 UTC, OleksiyRudenko commented
@Ant-C-tech did you test your code? Demo doesn't seem to work

2020-12-08 17:58 UTC, Ant-C-tech commented
I think it need some time for full load. Now it work, sorry.

2020-12-16 20:02 UTC, OleksiyRudenko requested changes
@Ant-C-tech a really good job!
Let's polish it.

2020-12-16 20:02 UTC, OleksiyRudenko commented on submissions/Ant-C-tech/frogger-game/app.js
> +for (let index = 0; index < _getRandomIntInclusive(ENEMY_MIN, ENEMY_MAX); index++) {
`_getRandomIntInclusive` in `index < _getRandomIntInclusive(ENEMY_MIN, ENEMY_MAX)` is called at every loop iteration. Not critical here but may cause issues in general case.

2020-12-16 20:02 UTC, OleksiyRudenko commented on submissions/Ant-C-tech/frogger-game/app.js
> +    };
How about ternary operator here? 
Besides `0 % 3 === 0`, `1 % 3 === 1` and `2 % 3 === 2`

2020-12-17 14:16 UTC, Ant-C-tech commented
Thank you for your review. I am not sure that I properly changed my code according your notice "How about ternary operator here?". It seems to me now it works without conditional construction.
Regards.

2020-12-17 16:56 UTC, OleksiyRudenko approved these changes
@Ant-C-tech great job done!

2020-12-17 16:56 UTC, merged

2020-12-17 17:34 UTC, Ant-C-tech commented
Thanks for your review and for the time that your spent to my code!

2020-12-17 18:05 UTC, OleksiyRudenko commented
@Ant-C-tech my pleasure. Hope it helped you to improve