add popup task to kriLEBED folder
kottans/frontend-2021-homeworks pull request #254
Opened 2020-12-09 10:47 UTC by kriLEBED

_Have your app published on [GitHub pages](https://github.com/kottans/frontend-2021-homeworks/blob/main/publish-your-app.md). Make sure your PR title contains the task name. Change task name and links below as appropriate. Remove this paragraph._

### task name

[Demo](https://your-username.github.io/app-repo-name)
[Code base](https://github.com/your-username/app-repo-name)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-09 19:23 UTC, lenadgit commented
When cursor moves on icons - they jump, and a scroll-bar jumps too 
( https://nimb.ws/NH3D7h ) 
This effect is not acceptable for web view.  That related to a header menu too. Could you please fix it?

2020-12-09 19:31 UTC, lenadgit requested changes
When the user hovers to the button Popup by Tab key - this button is not highlighted. Could you please add the same highlighting to this button? 
https://nimb.ws/fbQ4W1

2020-12-09 19:48 UTC, lenadgit requested changes

2020-12-09 19:48 UTC, lenadgit commented on submissions/kriLEBED/html_css_popup/css/style.css
> +a {
would be better to add the class with styles to the link instead of add styles to the tag (it is a good practice). could you please fix it?

2020-12-09 19:48 UTC, lenadgit commented on submissions/kriLEBED/html_css_popup/css/style.css
> +.wrapper{
between the class name and the bracket should be a space. Could you please add all necessary alignments and spaces by code formatting? (the option at your code editor)

2020-12-09 19:48 UTC, lenadgit commented on submissions/kriLEBED/html_css_popup/index.html
> +                                <input type="checkbox" id="more" class="more_btn"/>
All single tags should be without slashes ("/") due to HTML5 specification. Could you please fix it?

2020-12-09 19:48 UTC, lenadgit commented on submissions/kriLEBED/html_css_popup/index.html
> +</html>
if you see this symbol at the end of the file on Github - it means that the empty line is needed after the last tag (or any  last symbol at your file)
![empty line](https://user-images.githubusercontent.com/10871447/101679509-22d00500-3a68-11eb-8031-1416f4ff9156.png)
https://github.com/kottans/frontend-2021-homeworks/pull/254/files
Could you please add the empty line (without spaces)

2020-12-09 19:50 UTC, lenadgit commented
Almost excellent:)

2020-12-17 09:56 UTC, kriLEBED commented
I look forward to review)

2020-12-19 07:55 UTC, A-Ostrovnyy commented on submissions/kriLEBED/html_css_popup/index.html
> +    <link rel="preconnect" href="https://fonts.gstatic.com">
Avoid duplicating the same lines inside `head`.

2020-12-19 07:58 UTC, A-Ostrovnyy commented on submissions/kriLEBED/html_css_popup/index.html
> +                    <li class="menu_items" tabindex="1"><a href="#" class="menu-link">Mail</a></li>
You don't need a `tabindex` attribute here, because link(`a`) by default can receive focus, no need to change this behavior in this case.)

2020-12-19 08:00 UTC, A-Ostrovnyy commented on submissions/kriLEBED/html_css_popup/index.html
> +                        <input id="menu_toggle" type="checkbox" class="submenu_btn">
Watch the [video](https://www.youtube.com/watch?v=E6kLaaQFctU&t=413s) about hiding checkboxes in the right way.

2020-12-19 08:04 UTC, A-Ostrovnyy commented on submissions/kriLEBED/html_css_popup/css/style.css
> +.submenu-item a {
Avoid styling by #id or HTML tag. [Read more](https://frontstuff.io/you-need-to-stop-targeting-tags-in-css)
Also, separate responsibilities:

- HTML tag for markup;
- CSS class for styling;
- Id for JS logic

2020-12-19 08:07 UTC, A-Ostrovnyy requested changes
Good work!
1) I can't open popup using keyboard, Please fix it.
2) Remove all files that do not need to be reviewed such as images.

2020-12-28 12:31 UTC, OleksiyRudenko commented
@kriLEBED 
FYI
![image](https://user-images.githubusercontent.com/8686631/103214561-686e4800-4919-11eb-9c1b-a6f77bb886c0.png)

Please fix

2020-12-29 23:14 UTC, lenadgit commented
Now there is impossible to open popup by Keyboard. While the user moves through the menu by Tab key to open a popup, they should use the Space key. Could you please fix it? (add a possibility to open and close the popup by this key)

2020-12-29 23:14 UTC, lenadgit approved these changes

2021-01-02 09:31 UTC, OleksiyRudenko commented
@kriLEBED do you need any help with completing this?

2021-01-08 12:03 UTC, zonzujiro commented
For now I will close it, but fill free to open when you will be ready to continue

2021-01-08 12:03 UTC, closed without merging