f3d0t Html-css-popup HomeWork
kottans/frontend-2021-homeworks pull request #260
Opened 2020-12-10 16:00 UTC by f3d0t

### Html css popup

[Demo](https://f3d0t.github.io/f3d0t/html_css_popup/)
[Code base](https://github.com/f3d0t/f3d0t/tree/main/html_css_popup)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-10 18:07 UTC, lenadgit requested changes
Good job! remains only to format your code by autoformatting (html, css)

2020-12-10 18:50 UTC, f3d0t commented
Formatting done

2020-12-11 17:10 UTC, Temu4 requested changes
Well done, just one more thing ⬇️

2020-12-11 17:10 UTC, Temu4 commented on submissions/f3d0t/html-css-popup/index.html
> +                        <img alt="User avatar" class="popup__button--img avatar" src="img/apps.png">
Can you play around icon images and decrease unnecessary sizes?
<img width="649" alt="Screenshot 2020-12-11 at 19 07 19" src="https://user-images.githubusercontent.com/42999342/101933078-58016200-3be4-11eb-8a52-22acb84ae7fc.png">

2020-12-11 21:06 UTC, f3d0t commented
Pics size decreasing done

2020-12-11 21:10 UTC, Temu4 commented
> Pics size decreasing done

<img width="603" alt="Screenshot 2020-12-11 at 23 07 52" src="https://user-images.githubusercontent.com/42999342/101955159-fce06700-3c05-11eb-9f77-71a8a42feb13.png">

2020-12-11 22:14 UTC, f3d0t commented
images done =)

2020-12-14 12:35 UTC, Temu4 commented
Looks good to me! Well done! 👍

2020-12-14 12:35 UTC, merged