Html css popup
kottans/frontend-2021-homeworks pull request #261
Opened 2020-12-10 16:21 UTC by karachevtsev

### HTML-CSS-Popup

[Demo](https://karachevtsev.github.io/html-css-popup/)
[Code base](https://github.com/karachevtsev/html-css-popup)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-11 17:02 UTC, Temu4 requested changes
Really cool approach for this popup! Thanks for that! 👍 
But there a couple things that you can improve)

2020-12-11 18:13 UTC, Temu4 commented on submissions/karachevtsev/html-css-popup/index.html
> +                      <a href="#"><img src="images/mail.png" alt="" width="40" height="40">Mail</a>
No needed for decorative images [link](https://developers.google.com/web/fundamentals/accessibility/semantics-builtin/text-alternatives-for-images)

2020-12-14 22:18 UTC, karachevtsev commented on submissions/karachevtsev/html-css-popup/index.html
> +                      <a href="#"><img src="images/mail.png" alt="" width="40" height="40">Mail</a>
Added alt attribute for all images

2020-12-14 22:19 UTC, karachevtsev commented on submissions/karachevtsev/html-css-popup/index.html
> +                      <a href="#"><img src="images/news.png" alt="" width="40" height="40">News</a>
Set new icons images. Removed dimensions attributes from img tag and set dimension in css

2020-12-14 22:20 UTC, karachevtsev commented on submissions/karachevtsev/html-css-popup/scss/_nav-details.scss
> +    right: -40px;
Added media queries and updated mobile style

2020-12-22 09:24 UTC, Temu4 commented on submissions/karachevtsev/html-css-popup/scss/_nav-details.scss
> +    right: -40px;
+

2020-12-22 09:29 UTC, Temu4 commented on submissions/karachevtsev/html-css-popup/index.html
> +                      <a href="#"><img src="images/news.png" alt="" width="40" height="40">News</a>
Hi @karachevtsev!
The core of this issue isn't related with images sources, but with their real sizes.
Please try to decrease them. You can use such free and simple tools as Paint, for example.
<img width="655" alt="Screenshot 2020-12-22 at 11 25 45" src="https://user-images.githubusercontent.com/42999342/102872800-ec6f8e00-4448-11eb-873c-64ae67a858fa.png">

2020-12-22 23:19 UTC, A-Ostrovnyy commented
@Temu4 please finish review this PR)

2020-12-23 15:33 UTC, Temu4 commented
> Hi @karachevtsev!
> The core of this issue isn't related with images sources, but with their real sizes.
> Please try to decrease them. You can use such free and simple tools as Paint, for example.
> <img alt="Screenshot 2020-12-22 at 11 25 45" width="655" src="https://user-images.githubusercontent.com/42999342/102872800-ec6f8e00-4448-11eb-873c-64ae67a858fa.png">

Hey @karachevtsev !
Do you have some issues regarding that?
Please feel free to ping me in any messengers.

2020-12-24 17:02 UTC, karachevtsev commented
Hi @Temu4 !
Resolve isuue with icons sizes.

2020-12-24 20:08 UTC, merged

2020-12-24 20:08 UTC, Temu4 commented
Good job! 👍