JS post-OOP
kottans/frontend-2021-homeworks pull request #264
Opened 2020-12-11 16:49 UTC by zalevskyi

### JS post-OOP

[Demo](https://zalevskyi.github.io/kottans-frontend/practice/a-tiny-js-world/index.html)
[Code base](https://github.com/zalevskyi/kottans-frontend/tree/main/practice/a-tiny-js-world)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-13 15:03 UTC, OleksiyRudenko commented
@zalevskyi OOP Exercise is a task on its own.
Code for every task should be submitted in its own directory.
Please fix.

2020-12-13 16:09 UTC, OleksiyRudenko requested changes
@zalevskyi nice approach with composition.
Here is the problem. Species that do not have e.g. hands by natural design still have the property.
Imagine we add birds. Humans will then have undefined number of wings, birds will have undefined number of hands, etc. Then we add some more species and other props specific to particular species etc.
At the end every inhabitant will bear a burden of props they do not really have.
The point of OOP and SOLID, whether this is a class inheritance or composition pattern, is that every object has only those properties it really needs.
Can you resolve this issue within current scope?

2020-12-13 21:03 UTC, zalevskyi commented
Thank you for pointing out this issue.
Resolved.

2020-12-16 20:44 UTC, OleksiyRudenko requested changes
@zalevskyi well done!

A bit excessive taxonomy. Whenever any class is extended by a single child class then can be effectively merged. Keep this in mind.

In this task let assume it is OK.

Let's rather focus on more important things.

2020-12-16 20:44 UTC, OleksiyRudenko commented on submissions/zalevskyi/a-tiny-js-world-oop/index.js
> +      this.legs = 4
No good reasons to have any default value here. There is no good reasons to favour four-legged animals.
Obviously this should be initialized from constructor's arguments.

You will not have "override" it child class - no just good reason for this.

2020-12-16 20:44 UTC, OleksiyRudenko commented on submissions/zalevskyi/a-tiny-js-world-oop/index.js
> +      this.sound = sound
Both Hominoid and CarnivoraNonMarine have `sound`, which means it is a shared property and thus should be generalized to their common ancestor.

2020-12-25 11:45 UTC, zalevskyi commented
@OleksiyRudenko  Thank you for comments. Corrected. Please review once more

2020-12-28 07:56 UTC, OleksiyRudenko approved these changes
@zalevskyi well done!

2020-12-28 07:57 UTC, merged