fix-bug
kottans/frontend-2021-homeworks pull request #266
Opened 2020-12-11 19:36 UTC by SkirnevskyiAleksandr

###  Hooli-style-Popup

[Demo](https://skirnevskyialeksandr.github.io/Hooli-style-Popup/)
[Code base](https://github.com/SkirnevskyiAleksandr/Hooli-style-Popup)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-11 20:02 UTC, SkirnevskyiAleksandr commented
Hi, this is my second pull request, in the first one I made a mistake that I can't fix:
![pull request mistake](https://user-images.githubusercontent.com/55707796/101947876-d3b9d980-3bf9-11eb-945f-9fe3ed8bac08.png)
so I'm making a new pull request. Your comments on my code from first PR I fixed.

2020-12-13 16:13 UTC, OleksiyRudenko commented
This PR is a replacement for #239

2020-12-15 19:29 UTC, A-Ostrovnyy commented on submissions/SkirnevskyiAleksandr/HTML-CSS-Popup/index.html
> +          <li class="menu-item"><a class="menu-item" href="#">Images</a></li>
Fix `outline` on focus state. Same problem on icons inside the popup.
![image](https://user-images.githubusercontent.com/16196199/102263055-881a6f00-3f1c-11eb-8d11-e1be26d6aa96.png)

2020-12-15 19:31 UTC, A-Ostrovnyy commented on submissions/SkirnevskyiAleksandr/HTML-CSS-Popup/index.html
> +        <ul class="menu">
Different by functionality elements with the same class name is a bad practice. Please fix it.

2020-12-15 19:32 UTC, A-Ostrovnyy commented on submissions/SkirnevskyiAleksandr/HTML-CSS-Popup/index.html
> +    <title>Document</title>
Add a propper page title.

2020-12-15 19:49 UTC, A-Ostrovnyy requested changes
Good work!
See my comments above!

2020-12-16 19:49 UTC, A-Ostrovnyy commented on submissions/SkirnevskyiAleksandr/HTML-CSS-Popup/index.html
> +              <ul class="drop-down-menu">
Try to write class names or JS variables names in one style, It easier to read it in the future)

2020-12-16 19:49 UTC, A-Ostrovnyy requested changes
I see your changes in the demo but not in commits. Please add commit with changes to this repo.

2020-12-16 21:06 UTC, A-Ostrovnyy approved these changes
Well done!

2020-12-16 21:06 UTC, merged