add HTML & CSS practice: Hooli-style Popup
kottans/frontend-2021-homeworks pull request #27
Opened 2020-10-25 20:44 UTC by KikinovK

### Html-css-popup

[Demo](https://kikinovk.github.io/frontend-2021-homeworks/submissions/kikinovk/HTML_CSS_Popup/) |
[Code base](https://github.com/KikinovK/frontend-2021-homeworks/tree/html-css-popup-task/submissions/kikinovk/HTML_CSS_Popup)

The code is submitted in a dedicated feature branch.
Please, review.

2020-10-25 21:29 UTC, lenadgit commented on submissions/kikinovk/HTML_CSS_Popup/css/style.css
> +  font-family: sans-serif;;
could you please remove a second semicolon

2020-10-25 21:37 UTC, lenadgit commented on submissions/kikinovk/HTML_CSS_Popup/index.html
> +        <Label
could you please replace a capital letter

2020-10-25 21:38 UTC, lenadgit commented on submissions/kikinovk/HTML_CSS_Popup/index.html
> +</html>
could please add an empty line

2020-10-25 21:39 UTC, lenadgit commented on submissions/kikinovk/HTML_CSS_Popup/css/style.css
> +}
could you please add an empty line

2020-10-25 21:40 UTC, lenadgit commented
Excellent job in my opinion!

2020-10-26 07:49 UTC, MaxKalashnyk requested changes
Good job! Please fix all errors of your preview in the [validator](https://validator.w3.org/)

2020-10-26 20:30 UTC, KikinovK commented
> The empty line must be after the last tag/symbol. It s good practice https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file Could you please fix?

2020-10-26 20:53 UTC, lenadgit approved these changes

2020-10-26 21:22 UTC, MaxKalashnyk commented on submissions/kikinovk/HTML_CSS_Popup/css/style.css
> +  background-image: url(../image/bell-hover.png);
Changing different images by using `background-image` on each hover or focus can drastically decrease the performance of your styles. Better to use SVG icons here or some font icons and just toggle `fill` or `stroke` properties (for the SVGs) or color (for the font icons) on hover/focus/default states.
Let's leave these icons. But don't forget to use the SVG or font icons in the future, please

2020-10-26 21:25 UTC, MaxKalashnyk approved these changes

2020-10-26 21:26 UTC, merged