memory-pair-game
kottans/frontend-2021-homeworks pull request #289
Opened 2020-12-16 20:36 UTC by Iakow

### memory-pair-game

[Demo](https://iakow.github.io/memory-pair-game/)
[Code base](https://github.com/Iakow/frontend-2021-homeworks/tree/pair-game/submissions/iakow/memory-pair-game)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-16 20:50 UTC, OleksiyRudenko commented
@Iakow we do not need images for review. Submission of those makes cloning and sync-up time longer for other students (and for yourself).
![image](https://user-images.githubusercontent.com/8686631/102404857-f03a8500-3ff0-11eb-823c-ddc5af6853d5.png)

Please remove images from this PR

2020-12-16 20:57 UTC, Iakow commented
> @Iakow we do not need images for review. Submission of those makes cloning and sync-up time longer for other students (and for yourself).
> ![image](https://user-images.githubusercontent.com/8686631/102404857-f03a8500-3ff0-11eb-823c-ddc5af6853d5.png)
> 
> Please remove images from this PR

I'm sorry, done

2020-12-16 23:04 UTC, OleksiyRudenko commented
@Iakow A really nice gameplay and UX 👍

2021-02-11 19:25 UTC, Iakow commented
:warning: :warning: :warning: 
Refrain from reviewing for a few days, please, I will launch a totally different version.

2021-02-21 16:32 UTC, Iakow commented
@babayK0 :hand:

2021-02-24 15:59 UTC, babayK0 requested changes
Liked code structure and UI :+1: 
Watch my comments below

2021-02-24 15:59 UTC, babayK0 commented on submissions/iakow/memory-pair-game/js/game.js
> +      const score = Math.round(100000000 / (matchMoves * time));
100000000 - magic number

2021-02-24 15:59 UTC, babayK0 commented on submissions/iakow/memory-pair-game/js/game.js
> +  gameCards[openedCardsIDs[0]] = gameCards[openedCardsIDs[1]] = null;
use destructuring (with index it is not obvious)
`const [firstId, secondId] = openedCardsIDs`

2021-02-24 15:59 UTC, babayK0 commented on submissions/iakow/memory-pair-game/js/game.js
> +}
```suggestion
function checkIfLastPair() {
  return gameCards.filter((card) => card).length === 2;
}
```

2021-02-26 12:14 UTC, babayK0 approved these changes
:+1:

2021-02-26 12:15 UTC, merged

2021-02-27 11:01 UTC, Iakow commented
Thanks for review!