Frogger game
kottans/frontend-2021-homeworks pull request #290
Opened 2020-12-16 22:00 UTC by ORybka

### Object-Oriented JavaScript

[Demo](https://orybka.github.io/frogger-game/)
[Code base](https://github.com/ORybka/frogger-game)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-16 22:56 UTC, OleksiyRudenko requested changes
@ORybka a really good job!
Let's make it perfect.

2020-12-16 22:56 UTC, OleksiyRudenko commented on submissions/ORybka/frogger-game/app.js
> +  this.enemies = allEnemies;
A class should be agnostic of the outer world directly. Whatever it needs to know about outer world should be explicitly given to it at construction time. Just like `x` and `y` for it to appear at.

`allEnemies` is somethig from the outer world. Fix this.

Although, it is OK if class refers to global constants (that is their purpose - to be global) and engine API (`Resources` in this case).

2020-12-16 22:56 UTC, OleksiyRudenko commented on submissions/ORybka/frogger-game/app.js
> +  this.y = 380;
`200` and `300` have semantic meaning. I assume these are some initial position. Would be good to **read** it here.

Make sure all mysterious numbers have descriptive names (defined as constants) across the entire codebase. Many of them already do, just need to make this approach consistent.

2020-12-16 22:56 UTC, OleksiyRudenko commented on submissions/ORybka/frogger-game/app.js
> +      break;
Why do we need this here? It does really nothing

2020-12-16 22:56 UTC, OleksiyRudenko commented on submissions/ORybka/frogger-game/app.js
> +  }
How about `.forEach`? It would make the code cleaner and easier to read.

2020-12-18 18:38 UTC, ORybka commented
Thank you very much for the comments! :)
I am very glad with myself that I didn't have a lot of them, so finally I learnt some OOP :) 
I hope I understood right and took into consideration all the comments.

2020-12-18 19:42 UTC, OleksiyRudenko approved these changes
@ORybka perfectly done!

2020-12-18 19:42 UTC, merged