oop-practice. Repaired output. Using array of objects and forEach()
kottans/frontend-2021-homeworks pull request #293
Opened 2020-12-17 00:29 UTC by LGeorge007

### OOP-practice

[Demo](lgeorge007.github.io/oop-practice)
[Code base](https://github.com/LGeorge007/oop-practice)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-18 18:01 UTC, OleksiyRudenko requested changes
@LGeorge007 good work.
However some of the inconsistencies make me think you were in hurry.
Take your time and re-check your code for consitency.

Please also make your IDE to add empty lines at a file end for you.

![image](https://user-images.githubusercontent.com/8686631/102645833-c063bc80-416b-11eb-937a-3411424cd3f7.png)

2020-12-19 15:14 UTC, LGeorge007 commented on submissions/LGeorge007/oop-practice/index.js
> +       let haveFriend = (this.friends !== undefined) ? (this.friends.length === 1) ? "I have a friend. This is " + this.friends[0] : "I have friends. These are "+ this.friends.join(", ")   : "I'm alo
I've fixed my VS Code. And now it added new empty line in the end of file.
“files.insertFinalNewline”: true,
“files.trimFinalNewlines”: true,
“files.trimTrailingWhitespace”: true

I don't hear about it. But It was found of more convinient.
 let haveFriend = (this.friends !== undefined)
         ? (this.friends.length === 1)
            ? "I have a friend. This is " + this.friends[0]
            : "I have friends. These are "+ this.friends.join(", ")
         : "I'm alone. I have no friends";

2020-12-19 15:15 UTC, LGeorge007 commented on submissions/LGeorge007/oop-practice/index.js
> +       return `${this.greeting} ` + super.say() + ` I have ${this.paws} paws.`
I defined greeting in the Super class.
And use it in  say() function.
return `${this.greeting} I'm ${this.name}. I'm a ${this.species} and I have a ${this.gender} gender. ${haveFriend}.`;

2020-12-19 15:18 UTC, LGeorge007 commented on submissions/LGeorge007/oop-practice/index.js
> +      this.greeting = greeting;
Yes. I agreed with You. 
It does not make sense.
I defined greeting in the Inhabitant class.
And use it in say() function() there.

2020-12-19 19:48 UTC, OleksiyRudenko commented on submissions/LGeorge007/oop-practice/index.js
> +       let haveFriend = (this.friends !== undefined) ? (this.friends.length === 1) ? "I have a friend. This is " + this.friends[0] : "I have friends. These are "+ this.friends.join(", ")   : "I'm alo
> **I don't hear about it.** But It was found of more convinient.

What do you mean?

2020-12-19 20:02 UTC, LGeorge007 commented on submissions/LGeorge007/oop-practice/index.js
> +       let haveFriend = (this.friends !== undefined) ? (this.friends.length === 1) ? "I have a friend. This is " + this.friends[0] : "I have friends. These are "+ this.friends.join(", ")   : "I'm alo
This spelling is more convenient for reading. 
condition
  ? a
    ? x
    : v
  : t
  I haven't used this spelling before.

2020-12-21 09:28 UTC, OleksiyRudenko requested changes
@LGeorge007 nearly done.
One thing yet to fix.

2020-12-21 09:28 UTC, OleksiyRudenko commented on submissions/LGeorge007/oop-practice/index.js
> +                     ];
Every class of `Human`, `Dog`, `Cat`, `CatWoman` expect species explicitly passed to them.
It's unlikely we want a user be able to create a human with a different species. Same is tru fro dogs, cats and catwomen.
Why not letting `Human`, `Dog`, `Cat`, `CatWoman` classes to handle species by themselves?
They can pass respective species literals to their supers, expecting no species in their constructors.

2020-12-22 09:13 UTC, OleksiyRudenko approved these changes
@LGeorge007 well done!

2020-12-22 09:13 UTC, merged