Review my html/css popup please
kottans/frontend-2021-homeworks pull request #297
Opened 2020-12-17 12:03 UTC by alexey1985-FE

### HTML & CSS practice: Hooli-style Popup

[Demo](https://alexey1985-fe.github.io/HTML-CSS-Popup/.)
[Code base](https://github.com/alexey1985-FE/HTML-CSS-Popup)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-17 18:17 UTC, A-Ostrovnyy commented on submissions/alexey1985-FE/html-css-popup/css/style.css
> +    -webkit-box-pack: end;
Avoid writing properties with vendor prefixes.
Assign this to the bundler.

2020-12-17 18:20 UTC, A-Ostrovnyy commented on submissions/alexey1985-FE/html-css-popup/index.html
> +                      <div class="sub-menu__list">
Class name is `sub-menu__list` but HTML tag is `div`)

2020-12-17 18:25 UTC, A-Ostrovnyy commented on submissions/alexey1985-FE/html-css-popup/index.html
> +                          <input class="sub-menu__input" type="checkbox" id="sub-menu__input">
Fix grid inside sub-menu
![image](https://user-images.githubusercontent.com/16196199/102527559-ed4d9c00-40a5-11eb-9ce7-b81d228f1d00.png)

2020-12-17 18:26 UTC, A-Ostrovnyy requested changes
Good Work!
See my comments above!

2020-12-17 19:06 UTC, alexey1985-FE commented
Thanks for your review and advices.  I will fix it.  But it is strange that the grid went, in chrome and firefox it was all right.

2020-12-17 19:21 UTC, A-Ostrovnyy commented
Welcome to the web development world.)
Different browsers different implementations/interpretations of the specification.

2020-12-17 19:30 UTC, alexey1985-FE commented
It's true, but only chrome was specified in the task.  There was no cross-browser requirement for this task:)

2020-12-17 19:34 UTC, alexey1985-FE commented
![IMG_20201217_213226](https://user-images.githubusercontent.com/71827775/102534555-a06ec300-40af-11eb-8b67-17549506eaed.jpg)

2020-12-18 14:54 UTC, A-Ostrovnyy approved these changes
Well done

2020-12-18 14:54 UTC, merged

2020-12-18 14:57 UTC, alexey1985-FE commented
thank you very much for the quick response and advices