Initial commit
kottans/frontend-2021-homeworks pull request #307
Opened 2020-12-18 19:29 UTC by Jigsaff

### Document Object Model

[Demo](https://jigsaff.github.io/dom-api-task/)
[Code base](https://github.com/Jigsaff/dom-api-task)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-18 19:53 UTC, OleksiyRudenko commented
@Jigsaff thank you for your submission.

This is how your PR title looks among other PRs' titles.
![image](https://user-images.githubusercontent.com/8686631/102655602-40455300-417b-11eb-86d8-8d36a23fd15b.png)

PR message template also says
![image](https://user-images.githubusercontent.com/8686631/102655683-666af300-417b-11eb-99a1-ffeeb1af0c1e.png)

2020-12-18 19:54 UTC, OleksiyRudenko commented
Please also familiarize yourself with update instructions on this repo.

![image](https://user-images.githubusercontent.com/8686631/102655809-987c5500-417b-11eb-8937-80183967ac03.png)

Please fix this.

2020-12-18 20:07 UTC, Jigsaff commented
Fixed, please review.

2020-12-28 13:57 UTC, MaxKalashnyk requested changes
Good job! Appreciate you clean code.
Check my comments, please.
Also, pay attention to the mobile styles of your app for future. Now I see that your app doesn't look so nice on moblie devices.

2020-12-28 13:57 UTC, MaxKalashnyk commented on submissions/Jigsaff/dom-api-task/app/app.js
> +        const sectionName = target.textContent;
It's not a blocker for this task but you can toggle sections by using data attributes with some ids. And make checking by id, not by the textContent.

2020-12-28 13:57 UTC, MaxKalashnyk commented on submissions/Jigsaff/dom-api-task/app/app.js
> +            (item) => item.name.toLowerCase() === sectionName.toLowerCase()
You can destructure your `item` object here. Also, I'd recommend using not so generic names for variables. Using the `item` variable name is not very informative

2020-12-29 13:55 UTC, MaxKalashnyk approved these changes
LGTM!

2020-12-29 13:55 UTC, MaxKalashnyk commented on submissions/Jigsaff/dom-api-task/app/app.js
> +            ({name: backpackName}) => backpackName.toLowerCase() === sectionName.toLowerCase()
👍🏻

2020-12-29 13:56 UTC, merged