Frogger initial commit
kottans/frontend-2021-homeworks pull request #313
Opened 2020-12-19 07:00 UTC by yaripey

### Frogger

[Demo](https://yaripey.github.io/frontend-nanodegree-arcade-game/)
[Code base](https://github.com/yaripey/frontend-nanodegree-arcade-game)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-21 21:53 UTC, andrewklmn commented
@yaripey 
Good job!
All bugs are running and frogger is moving well!

![no_difference](https://user-images.githubusercontent.com/2924306/102825095-c7e2ca00-43e6-11eb-9f10-2e8e98463013.gif)
But there is no difference if I lose or win.
In all these cases I just return to the start position.
Maybe it's better to add an alert() with congratulations when I win?

It's not a code review. Just wondering.

2020-12-22 13:24 UTC, yaripey commented
Yeah, I like the idea. Will implement.

2020-12-23 21:50 UTC, andrewklmn requested changes
Good job!
Your code is well-formatted and easy to read. Thank you!

Let's make this good code more object-oriented!
Check my comments below and feel free to ask any questions.

2020-12-23 21:50 UTC, andrewklmn commented on submissions/yaripey/frogger/app.js
> +    this.speed = Math.random() * (400 - 100) + 100;
magic numbers...
All numbers like block dimensions, initial locations should be defined as constants.

2020-12-23 21:50 UTC, andrewklmn commented on submissions/yaripey/frogger/app.js
> +    if (this.x > tile.width * 5) {
magic number '5'....

2020-12-23 21:50 UTC, andrewklmn commented on submissions/yaripey/frogger/app.js
> +        this.x = -tile.width * 1
do we really need this multiplication by 1 here?

2020-12-23 21:50 UTC, andrewklmn commented on submissions/yaripey/frogger/app.js
> +const player = new Player(tile.width * 2, tile.height * 4.5)
initial locations should be defined as constants

2020-12-23 21:50 UTC, andrewklmn commented on submissions/yaripey/frogger/app.js
> +            && Math.abs(Math.abs(enemy.y) - Math.abs(player.y)) < 60
magic number '60'...
Is it COLLISION_DISTANCE? maybe it's better to use a defined constant instead? e.g.:
const COLLISION_DISTANCE = 60;

2020-12-23 21:50 UTC, andrewklmn commented on submissions/yaripey/frogger/app.js
> +    this.sprite = 'images/enemy-bug.png';
this.x, this.y, this.sprite - properties that can be generalized into a base class. For example, the class 'Character' can be a base class, which is extended by Enemy and Player classes. And you can use inheritance for them both.

Class extension can be implemented using Subclass.prototype = Object.create(Superclass.prototype);
[Here is useful article](https://ui.dev/javascript-inheritance-and-the-prototype-chain/) about functional inheritance.

2020-12-23 21:50 UTC, andrewklmn commented on submissions/yaripey/frogger/app.js
> +    this.sprite = "images/char-boy.png";
Definition of this.x, this.y, this.sprite - in 'Player' also can be moved to the base 'Character' class...

2020-12-23 21:50 UTC, andrewklmn commented on submissions/yaripey/frogger/app.js
> +}
Method 'render()' of 'Player' class is the same as method 'render()' of Enemy... 
So we can avoid this repetition of code just by moving this method to the prototype of the base 'Character' class.

2020-12-23 21:57 UTC, andrewklmn commented
> Yeah, I like the idea. Will implement.

@yaripey 
Well done!
It works now! )))

![well_done](https://user-images.githubusercontent.com/2924306/103039766-52a7fe00-457a-11eb-805d-a5686be9422b.png)

2020-12-24 09:09 UTC, andrewklmn approved these changes
@yaripey 
LGTM!
Good job!
Now your code looks more DRYer!...
I approve.

2020-12-24 09:11 UTC, andrewklmn commented
@A-Ostrovnyy 
@OleksiyRudenko 
@zonzujiro 

Could you check approve and merge this PR, please?

2020-12-24 09:17 UTC, merged