added html-css-popup
kottans/frontend-2021-homeworks pull request #333
Opened 2020-12-22 14:43 UTC by Harnytskyi

### task html-css-popup

[Demo](https://harnytskyi.github.io/kottans-frontend/html_css_popup/)
[Code base](https://github.com/Harnytskyi/kottans-frontend/tree/main/html_css_popup)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-22 16:24 UTC, HannaSyn commented
Hello! Good job! ) See some comments below :)

2020-12-22 16:26 UTC, HannaSyn commented
You should add `:focus` to menu, like in example
<img width="289" alt="Screenshot 2020-12-22 at 18 21 21" src="https://user-images.githubusercontent.com/62648675/102910377-22316880-4483-11eb-8925-67bca34c9080.png">
<img width="439" alt="Screenshot 2020-12-22 at 18 21 56" src="https://user-images.githubusercontent.com/62648675/102910381-23629580-4483-11eb-8830-21e1f230343d.png">

2020-12-22 16:30 UTC, HannaSyn commented on submissions/Harnytskyi/html_css_popup/index.html
> +                        <div class="popup-ul">
Why you don't use `ul` and `li` tags for list there?

2020-12-22 16:49 UTC, HannaSyn commented on submissions/Harnytskyi/html_css_popup/css/style.css
> +.popup-check:checked~.popup{
I did focus like this: 

> input:focus ~ label {
    _some styles for you focus state here_
}

2020-12-22 20:38 UTC, lenadgit requested changes

2020-12-22 20:38 UTC, lenadgit commented on submissions/Harnytskyi/html_css_popup/index.html
> +    <head>
Unicode is mandatory for symbols in html document, could you please add it?
`<meta charset="UTF-8">`

2020-12-22 20:55 UTC, lenadgit requested changes

2020-12-22 20:55 UTC, lenadgit commented on submissions/Harnytskyi/html_css_popup/index.html
> +        <link rel="stylesheet" href="css/style.css">
Metatag Viewport sets up the correct setting for the mobile view. 
https://serpstat.com/ru/blog/chto-takoe-metateg-viewport/
Although CSS styles for mobile is not required for this task, this meta tag is required for markup in general
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`

2020-12-22 20:57 UTC, lenadgit requested changes

2020-12-22 20:57 UTC, lenadgit commented on submissions/Harnytskyi/html_css_popup/index.html
> +    <head>
Metatag Viewport sets up the correct setting for the mobile view.
https://serpstat.com/ru/blog/chto-takoe-metateg-viewport/
Although CSS styles for mobile is not required for this task, this meta tag is required for markup in general
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`

2020-12-22 21:00 UTC, lenadgit requested changes

2020-12-22 21:00 UTC, lenadgit commented on submissions/Harnytskyi/html_css_popup/index.html
> +    <head>
Also -- required meta tag for support IE:
`<meta http-equiv="X-UA-Compatible" content="ie=edge">`

2020-12-22 21:08 UTC, lenadgit requested changes

2020-12-22 21:08 UTC, lenadgit commented on submissions/Harnytskyi/html_css_popup/index.html
> +                    <input class="popup-check" id="popup-check" type="checkbox" />
Single tags should be without slashes "/" (according to HTML5 specification). https://codebra.ru/en/lessons-html/dating/2/1
Could you please remove it?

2020-12-22 21:16 UTC, lenadgit commented
All 'alt' attributes for images should be fill in the appropriate text. It is required for [a11y](https://developer.mozilla.org/en-US/docs/Web/Accessibility), they understand the context of images using screen-readers.
Could you please add the relevant text to each 'alt'?

2020-12-22 21:20 UTC, lenadgit requested changes

2020-12-22 21:20 UTC, lenadgit commented on submissions/Harnytskyi/html_css_popup/index.html
> +                    <div class="popup">
It would be better to use tags `nav > ul > li` for menu-icons in the popup. Could you please add these tags

2020-12-22 21:24 UTC, lenadgit requested changes

2020-12-22 21:24 UTC, lenadgit commented on submissions/Harnytskyi/html_css_popup/index.html
> +                    <a href="#"><img alt="profile" class="menu-button-img" style="max-width: 32px; max-height: 32px" src="./img/profile.png"></a>
inline-styles are not allowed for HTML5 specification, could you please fix it?

2020-12-22 21:25 UTC, lenadgit requested changes

2020-12-22 21:25 UTC, lenadgit commented on submissions/Harnytskyi/html_css_popup/index.html
> +                    <a href="#"><img alt="bell" style="width: 18px" class="menu-button-img" src="./img/bell.png"></a>
inline-styles are not allowed for HTML5 specification, could you please fix it?

2020-12-22 21:29 UTC, lenadgit requested changes

2020-12-22 21:29 UTC, lenadgit commented on submissions/Harnytskyi/html_css_popup/css/style.css
> +.menu{
Between selector and a bracket should be a space. Could you please format this file by any auto formatting?

2020-12-24 20:53 UTC, lenadgit approved these changes
well done)

2020-12-24 20:53 UTC, merged