Initial OOP tiny js world commit
kottans/frontend-2021-homeworks pull request #347
Opened 2020-12-24 15:08 UTC by yaripey

### OOP-exercise

[Demo](https://yaripey.github.io/a-tiny-JS-world/)
[Code base](https://github.com/yaripey/a-tiny-JS-world)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-24 19:13 UTC, OleksiyRudenko commented
@yaripey your demo leads to a web page based on a different code base.

2020-12-24 19:17 UTC, OleksiyRudenko requested changes
@yaripey please test your app

2020-12-24 19:17 UTC, OleksiyRudenko commented on submissions/yaripey/oop-exercise/index.js
> +print(boy.aboutMe)
Why such a stepback in iteration through inhabitants?

2020-12-24 19:17 UTC, OleksiyRudenko commented on submissions/yaripey/oop-exercise/index.js
> +    this.hands = hands
Not every inhabitant has hands by natural design. The beauty of OOP is that every class has props it really needs.
QUick scan didn't show any hands count output

2020-12-24 19:17 UTC, OleksiyRudenko commented on submissions/yaripey/oop-exercise/index.js
> +    console.log(this.friendship ? true : false)
Debugging artifact? Please remove

2020-12-25 07:51 UTC, yaripey commented
Links in PR are right, I just messed up with branches a little bit, GitHub pages was pointing on the wrong one. Now it should work correctly.

2020-12-25 08:09 UTC, OleksiyRudenko commented
@yaripey what about legs output?
Please feel free asking yourself this type of question with regards to every property individually and task requirements overall.

2020-12-28 08:15 UTC, OleksiyRudenko approved these changes
@yaripey well done. Approved with a reservation.

`.legs` prop is treated in different ways for humans and pets (where those are a substitute for paws). Perhaps these should be different props (`paws` for pets, still `legs` for humans).

Imagine you introduce birds and use `hands` as a substitute for wings. This makes code not really obvious.

2020-12-28 08:15 UTC, merged

2020-12-28 08:50 UTC, yaripey commented
Understood, I will consider it in future projects. Thanks!