html-css-popup task from antonkottans added
kottans/frontend-2021-homeworks pull request #350
Opened 2020-12-25 04:50 UTC by AntonKottans

_Have your app published on [GitHub pages](https://github.com/kottans/frontend-2021-homeworks/blob/main/publish-your-app.md). Make sure your PR title contains the task name. Change task name and links below as appropriate. Remove this paragraph._

### task name

[Demo](https://antonkottans.github.io/hooli-style-popup/)
[Code base](https://github.com/AntonKottans/hooli-style-popup)

The code is submitted in a dedicated feature branch.
Please, review.

2020-12-25 12:56 UTC, lenadgit requested changes
Could you please add the padding to a top row? Icons sticks to the top
![top-icons](https://user-images.githubusercontent.com/10871447/103135487-54c8a480-46c1-11eb-9180-d9856aec67a6.jpg)

2020-12-25 13:02 UTC, lenadgit requested changes

2020-12-25 13:02 UTC, lenadgit commented on submissions/AntonKottans/html-css-popup/index.html
> +		<meta charset="UTF-8" />
According to the HTML specification - all single tags should be without slashes "/". Could you please remove all these slashes?
 https://codebra.ru/en/lessons-html/dating/2/1

2020-12-25 13:04 UTC, lenadgit requested changes
According to the HTML specification - all single tags should be without slashes "/". Could you please remove all these slashes?
https://codebra.ru/en/lessons-html/dating/2/1

2020-12-25 13:14 UTC, lenadgit requested changes

2020-12-25 13:14 UTC, lenadgit commented on submissions/AntonKottans/html-css-popup/index.html
> +									alt=""
Each attribute `alt` should contains a text, it is necessary for [a11y](https://developer.mozilla.org/en-US/docs/Web/Accessibility) . Disabilities view the web-page by screen-reader and it helps them to understand the context of each picture.
Could you please add the appropriated text to each `alt`

2020-12-25 13:20 UTC, lenadgit requested changes
Could you please format CSS-file by auto-formatting? (to add the same alignments to all lines)

2020-12-25 13:36 UTC, lenadgit commented
In general the functionality is good, especially the animation for appearing of popup is a good opinion as a UX\UI solution. It remains to work a little on syntax of HTML5

2020-12-26 14:59 UTC, A-Ostrovnyy requested changes
Good work!

2020-12-26 14:59 UTC, A-Ostrovnyy commented on submissions/AntonKottans/html-css-popup/style.css
> +hr.popup-hr {
Avoid writing too specific CSS selectors. Also, avoid styling by HTML tag or `#id` [Read more](https://frontstuff.io/you-need-to-stop-targeting-tags-in-css)

2020-12-26 21:21 UTC, A-Ostrovnyy approved these changes
Well done!

2020-12-26 21:22 UTC, A-Ostrovnyy commented
@lenadgit your turn)

2020-12-27 19:42 UTC, lenadgit approved these changes

2020-12-27 19:42 UTC, merged