Memory pair game
kottans/frontend-2021-homeworks pull request #428
Opened 2021-01-11 19:57 UTC by zalevskyi

### Memory pair game

[Demo](https://zalevskyi.github.io/kottans-frontend/practice/memory-pair-game/index.html)
[Code base](https://github.com/zalevskyi/kottans-frontend/tree/main/practice/memory-pair-game)

The code is submitted in a dedicated feature branch.
Please, review.

2021-02-08 16:43 UTC, babayK0 requested changes
Good job !
Watch my comments below)

2021-02-08 16:43 UTC, babayK0 commented on submissions/zalevskyi/memory-pair-game/app.js
> +//Card deck for memory pair matching
Redundant comment

2021-02-08 16:43 UTC, babayK0 commented on submissions/zalevskyi/memory-pair-game/app.js
> +        //board is div element for appending child card elements
Redundant comment

2021-02-08 16:43 UTC, babayK0 commented on submissions/zalevskyi/memory-pair-game/app.js
> +    //extracts Id number from HTML element id
Redundant comment

2021-02-08 16:43 UTC, babayK0 commented on submissions/zalevskyi/memory-pair-game/app.js
> +        //index - card index in current deal of the deck
Redundant comment

2021-02-08 16:43 UTC, babayK0 commented on submissions/zalevskyi/memory-pair-game/app.js
> +        if (cardId!==undefined) DECK.openCard(cardId)
```suggestion
        if (cardId) DECK.openCard(cardId)
```

2021-02-08 16:43 UTC, babayK0 commented on submissions/zalevskyi/memory-pair-game/app.js
> +        if (this.opened.length==2 && Card.match(this.opened[0], this.opened[1])) {
will be more readable with destructuring
`const [firstCard, secondCard] = this.opened;`

use strict equality operator

2021-02-08 16:43 UTC, babayK0 commented on submissions/zalevskyi/memory-pair-game/app.js
> +    _hideOpened() {while(this.opened.length > 0) this.opened.pop().hide()}
format your code please, not readable

2021-02-08 16:43 UTC, babayK0 commented on submissions/zalevskyi/memory-pair-game/app.js
> +    _closeOpened() {while(this.opened.length > 0) this.opened.pop().close()}
```suggestion
    _closeOpened() {while(this.opened.length) this.opened.pop().close()}
```

2021-02-11 17:05 UTC, zalevskyi commented
Thank you for the review!
All recommendations are implemented.
Please review once more

2021-02-12 14:04 UTC, babayK0 approved these changes
Good job!

2021-02-12 14:04 UTC, merged