html/css popup
kottans/frontend-2021-homeworks pull request #43
Opened 2020-10-30 09:55 UTC by Nemooochka

_Complete the form below and remove this line._

### html/css popup

[Demo](https://nemooochka.github.io/frontend-2021-homeworks/submissions/Nemooochka/html-css-popup/) |
[Code base](https://github.com/Nemooochka/frontend-2021-homeworks/tree/html-css-popup)

The code is submitted in a dedicated feature branch.
Please, review.

2020-10-30 10:22 UTC, MaxKalashnyk requested changes
Nice work! Look at my comments below, pleae

2020-10-30 10:22 UTC, MaxKalashnyk commented on submissions/Nemooochka/html-css-popup/css/style.css
> +.nav-menu li .toggleMenu_label {
You can simplify this selector just to the class
```suggestion
.toggleMenu_label {
```

2020-10-30 10:22 UTC, MaxKalashnyk commented on submissions/Nemooochka/html-css-popup/css/style.css
> +.nav-menu li #toggleMenu:checked ~ label {
You can simplify this selector as well. And avoid using id's for styling, please. t's better to use classes.
```suggestion
#toggleMenu:checked ~ label {
```

2020-10-30 10:22 UTC, MaxKalashnyk commented on submissions/Nemooochka/html-css-popup/css/style.css
> +.nav-menu li #toggleMenu:checked ~ .popup-menu {
The same as in the previous comment

2020-10-30 10:22 UTC, MaxKalashnyk commented on submissions/Nemooochka/html-css-popup/css/style.css
> +    z-index: 999;
It's better to use not a magic number here. Maybe a value of 1 or 2 for this `z-index` will be ok

2020-10-30 10:22 UTC, MaxKalashnyk commented on submissions/Nemooochka/html-css-popup/css/style.css
> +.menu li a {
You can assign some class name for this link and simplify this selector
```suggestion
.someClassName {
```

2020-10-30 10:22 UTC, MaxKalashnyk commented on submissions/Nemooochka/html-css-popup/css/style.css
> +.menu.menu-extra {
The same here.
```suggestion
.menu-extra {
```

2020-10-30 10:22 UTC, MaxKalashnyk commented on submissions/Nemooochka/html-css-popup/css/style.css
> +}
Add an empty line here

2020-10-30 10:22 UTC, MaxKalashnyk commented on submissions/Nemooochka/html-css-popup/css/style.css
> +#showMore:checked ~ label {
Avoid styling elements by id as well

2020-10-30 10:22 UTC, MaxKalashnyk commented on submissions/Nemooochka/html-css-popup/index.html
> +</html>
Add an empty line here

2020-10-30 10:22 UTC, MaxKalashnyk commented on submissions/Nemooochka/html-css-popup/index.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"
It's not a blocker, but you can use some simpler styles normalizer but without external links for them.

2020-10-30 10:22 UTC, MaxKalashnyk commented on submissions/Nemooochka/html-css-popup/index.html
> +    <script src="https://kit.fontawesome.com/559af75b05.js" crossorigin="anonymous"></script>
It's also not a blocker, but try to avoid some external script for simple icon fonts. It can decrease the loading time of your page

2020-10-31 06:08 UTC, Nemooochka commented
Hi @MaxKalashnyk,

Thank you for so detailed check! Updates, pls re-review.

2020-11-01 09:57 UTC, MaxKalashnyk requested changes
It seems you didn't fix all issues. Please, take a look at your PR again.

2020-11-01 09:57 UTC, MaxKalashnyk commented on submissions/Nemooochka/html-css-popup/css/style.css
> +.menu.menu-extra {
Please fix it as well

2020-11-01 09:57 UTC, MaxKalashnyk commented on submissions/Nemooochka/html-css-popup/css/style.css
> +.nav-menu li .toggleMenu_label {
Please fix it as well

2020-11-02 15:48 UTC, Nemooochka commented
@MaxKalashnyk, thanks! Update, please re-check :)

2020-11-02 15:57 UTC, MaxKalashnyk approved these changes
LGTM!

2020-11-02 15:58 UTC, merged