friends-app by LGeorge007
kottans/frontend-2021-homeworks pull request #446
Opened 2021-01-31 21:07 UTC by LGeorge007

### friends-app

[Demo](lgeorge007.github.io/friends-app)
[Code base](https://github.com/LGeorge007/friends-app)

The code is submitted in a dedicated feature branch.
Please, review.

2021-02-01 06:33 UTC, zonzujiro requested changes
Leaved couple comments.

Also, I see common mistakes. Please check this list:

- Single responsibility - your functions should do only one job. As an example function in which you fetch users should only fetch them and not render, transform or process them in other ways. All this things should be done in another place, outside your function. Same applied to sort function, which usually do all types of sorting 😉
- You should handle fetch response status - https://www.tjvantoll.com/2015/09/13/fetch-and-errors/
- Don’t use names as arr, array, data or etc. They to generic. Don’t use things like sortingByABC and sortingByZYX - it’s unclear and just weird. `user1` and `user2` - don't use numbers in names. Just don't :) friendsArr also bad idea - you show data type in variable name and in JS it’s redundant
- Prefer template strings to “createElement” API
- Your template strings which contains should have intendations as in HTML
- When you need to decide which sort condition were selected, prefer value of input to “check class name of pressed element”, or “compare pressed element to saved element” etc. You can have value “female”, get value and then just use it
- Don’t overuse global variables, keep data which you are using closest as possible to place where you using it. As an example, request url can be inside function which sends request
- Redundant comments - don’t use stuff ‘———————————‘ or “here I will sort my array”. First one is ugly, second - redundant because reviewer will understand that you do sort, from your code. Only situation in which you should use comments, is when you need to describe why something is going on and this is 1% of all situations :)
- Please, doublecheck english wordings. Use code spellchecker, etc.

And remember, the best way to speed up review, is to fix errors prior review. 90% of errors are shared - go thru closed PRs with Friends App and check discussions there. You will find a places with same mistakes

2021-02-01 06:33 UTC, zonzujiro commented on submissions/LGeorge007/friends-app/script.js
> +    let selectedChoice = Array.from(elements.sortBy).filter(({checked}) => checked);
Can be replaced with query selector

2021-02-01 06:33 UTC, zonzujiro commented on submissions/LGeorge007/friends-app/script.js
> +    switch(selectedChoice[0].id) {
Prefer property `value` with 'ascending`, etc. values

2021-02-01 06:33 UTC, zonzujiro commented on submissions/LGeorge007/friends-app/script.js
> +    };
`state.gotResult = result.filter( unit => unit.gender == state.filterBySex);`

2021-02-01 06:33 UTC, zonzujiro commented on submissions/LGeorge007/friends-app/script.js
> +        state.gotResult.sort((a, b) => sortByAge(a, b));
```suggestion
        state.gotResult.sort(sortByAge);
```

2021-02-01 06:33 UTC, zonzujiro commented on submissions/LGeorge007/friends-app/script.js
> +                        : 1;
Don't use nested ternaries. They hard to read

2021-02-01 06:33 UTC, zonzujiro commented on submissions/LGeorge007/friends-app/script.js
> +    }
Usually state should not have any functions

2021-02-01 06:33 UTC, zonzujiro commented on submissions/LGeorge007/friends-app/script.js
> +let result = [];
Why not in state? 🤔

2021-02-01 06:33 UTC, zonzujiro commented on submissions/LGeorge007/friends-app/script.js
> +    form.elements[9].checked = "true";
Direct access to DOM

2021-02-01 21:09 UTC, mustbefail commented on submissions/LGeorge007/friends-app/script.js
> +}
You can use .localeCompare(), the function returns exactly 0 1 -1. And you don't need .toLoweCase()
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare

2021-02-21 20:41 UTC, zonzujiro approved these changes
LGTM

2021-02-21 20:41 UTC, zonzujiro commented on submissions/LGeorge007/friends-app/script.js
> +}
They not sorting, they comparing ;)

2021-02-21 20:41 UTC, zonzujiro commented on submissions/LGeorge007/friends-app/script.js
> +const reset = function () {
Reset what? :)

2021-02-21 20:41 UTC, merged