Added friends app
kottans/frontend-2021-homeworks pull request #454
Opened 2021-02-15 16:46 UTC by SerhiiYakovenko

# Friends app task.

[Demo](https://serhiiyakovenko.github.io/friends-app/)  |  [Code](https://github.com/SerhiiYakovenko/friends-app/)

The code is submitted in a dedicated feature branch.
Please, review.

2021-02-16 17:00 UTC, zonzujiro requested changes

2021-02-16 17:00 UTC, zonzujiro commented on submissions/SerhiiYakovenko/friends-app/script.js
> +  .catch((error) => console.log(error));
Put into some function with meaningful name

2021-02-16 17:00 UTC, zonzujiro commented on submissions/SerhiiYakovenko/friends-app/script.js
> +}
The sort function should do only sorting.

Also, it should be one function. The only order of arguments matters

2021-02-16 17:00 UTC, zonzujiro commented on submissions/SerhiiYakovenko/friends-app/script.js
> +}
One function

2021-02-16 17:00 UTC, zonzujiro commented on submissions/SerhiiYakovenko/friends-app/script.js
> +  nameDescending.addEventListener("click", () => sortNameDesc(users));
Please, use event delegation.
Also, you can listen for `change` event.

2021-02-16 17:01 UTC, zonzujiro commented on submissions/SerhiiYakovenko/friends-app/index.html
> +      <span class="name-asc">&#9650;</span>
Because of a11y this also should be inputs.

2021-02-18 23:09 UTC, SerhiiYakovenko commented
Thanks for the advice @zonzujiro, please review 🥺

2021-02-19 09:57 UTC, zonzujiro requested changes

2021-02-19 09:57 UTC, zonzujiro commented on submissions/SerhiiYakovenko/friends-app/script.js
> +      return b.name.first < a.name.first ? -1 : 1
Same function as at previous line. DRY

2021-02-19 09:57 UTC, zonzujiro commented on submissions/SerhiiYakovenko/friends-app/script.js
> +    createCards(sortByAge(users, event.target.className))
Please, use class names only for styling. For your purposes you can choose `data-*`

2021-02-19 15:20 UTC, SerhiiYakovenko commented
Updated, @zonzujiro can you please take a look?

2021-02-22 10:58 UTC, zonzujiro approved these changes
LGTM

2021-02-22 10:58 UTC, merged