Memory Pair Game
kottans/frontend-2021-homeworks pull request #456
Opened 2021-02-15 20:23 UTC by ORybka

### Memory Pair Game

[Demo](https://orybka.github.io/memory-pair-game/)
[Code base](https://github.com/ORybka/memory-pair-game)

The code is submitted in a dedicated feature branch.
Please, review.

2021-02-23 16:48 UTC, babayK0 requested changes
Good job and very nice that you try to use js animations !
But watch my comments below to improve your code =)

2021-02-23 16:48 UTC, babayK0 commented on submissions/ORybka/memory-pair/main.js
> +          <img src="assets/cards/${el}.jfif" alt="card" class="card-image"/>
it is better to store full `src` path in your array/object

2021-02-23 16:48 UTC, babayK0 commented on submissions/ORybka/memory-pair/main.js
> +    if (cardPairArray[0].dataset.cardValue === cardPairArray[1].dataset.cardValue) {
use destructuring please
`const [firstCard, secondCard] = cardPairArray;`

2021-02-23 16:48 UTC, babayK0 commented on submissions/ORybka/memory-pair/main.js
> +function movesNumber() {
function name must be verb

2021-02-23 16:48 UTC, babayK0 commented on submissions/ORybka/memory-pair/main.js
> +function ifWon() {
verb

2021-02-23 16:48 UTC, babayK0 commented on submissions/ORybka/memory-pair/main.js
> +      }, DELAY / 2);
wow, why not create css classes and just add them here ?

2021-02-23 16:48 UTC, babayK0 commented on submissions/ORybka/memory-pair/main.js
> +    if (previousCat === '') {
`  if (!previousCat) {`

2021-02-23 16:48 UTC, babayK0 commented on submissions/ORybka/memory-pair/main.js
> +function addCat() {
Don't Repeat Yourself. So, make this function DRYer, please.

2021-02-26 05:54 UTC, ORybka commented
@babayK0 thank you very much for your comments 😸 I hope, I rewrote everything in the right way :)

2021-02-26 12:34 UTC, babayK0 approved these changes
:+1:

2021-02-26 12:34 UTC, merged