add first commit
kottans/frontend-2021-homeworks pull request #460
Opened 2021-02-18 13:52 UTC by Roophee

### Friends App

[Demo](https://roophee.github.io/friends-app/)
[Code base](https://github.com/Roophee/frontend-2021-homeworks/tree/friends-app-old-school/submissions/Roophee/friends-app)

The code is submitted in a dedicated feature branch.
Please, review.

2021-02-23 19:11 UTC, babayK0 requested changes
Cool design ! I like it   :sunglasses:

First of all i want ask you why all filters resets when i start type in search input ? 
Also watch my comments below

2021-02-23 19:11 UTC, babayK0 commented on submissions/Roophee/friends-app/index.js
> +        filterSettings.filterTwo = filter.name;
i don't see this props in initial `filterSettings`

`filterOne`
`filterTwo`

and what is the difference between these ones?

2021-02-24 13:24 UTC, babayK0 commented on submissions/Roophee/friends-app/index.js
> +                        secondFilteredData: []};
@Roophee can you answer please ?
why these variables called like this 
not obvious

2021-02-24 13:45 UTC, Roophee commented on submissions/Roophee/friends-app/index.js
> +                        secondFilteredData: []};
@babayK0 I was trying to implement filtering an array with two filters. The first filter stores the filtered result in a `filteredData: []` array. The second filter make filtration with the data after the first filter and saves it to the second array `secondFilteredData: []`  to display it on the screen, and then the method is applied to get Nodes from NODE_STORAGE.

2021-02-24 13:47 UTC, babayK0 requested changes
Need more DRY :rofl:

2021-02-24 13:47 UTC, babayK0 commented on submissions/Roophee/friends-app/index.js
> +const wasSecondFiltration = () => filterSettings.secondFilteredData.length >= 1;
1. verb
1. `wasFiltration` ? maybe `getIsFiltered` will be better name for this one
1. if you use functions you can do things like this
```suggestion
const getIsFiltered = (data) => data.length >= 1;
```
or 
```suggestion
const getIsFiltered = (settingDataKey) => filterSettings[settingDataKey].length >= 1;
```

2021-02-24 13:47 UTC, babayK0 commented on submissions/Roophee/friends-app/index.js
> +const thisFilterMadeSecondFiltration = (filter) => filterSettings.filterTwo === filter.name;
1. verb
2. 
```suggestion
const checkWichFiltrationWasMade = (filter, comparativeFilterName) => comparativeFilterName === filter.name;

```
or
```suggestion
const checkWichFiltrationWasMade = (filter, filterKey) => filterSettings[filterKey] === filter.name;

```

2021-02-24 13:47 UTC, babayK0 commented on submissions/Roophee/friends-app/index.js
> +    }
1. verb
2. make more dry please) `const foo = (a , b) => a === b`

2021-02-24 13:47 UTC, babayK0 commented on submissions/Roophee/friends-app/index.js
> +    }
1. verbs
2. dry

2021-02-24 13:47 UTC, babayK0 commented on submissions/Roophee/friends-app/index.js
> +}
```suggestion
const uncheckSortByRadio = (radioName) => {
    document.querySelectorAll('input[name=radioName]').forEach((item) => {
        item.checked = false;
    });
}

2021-02-24 13:48 UTC, Roophee commented on submissions/Roophee/friends-app/index.js
> +                        secondFilteredData: []};
@babayK0  Sorting methods are applied depending on whether the first filtration and / or the second filtration was performed. That is, the methods are applied to arrays where filtering results are stored.

2021-02-24 15:33 UTC, babayK0 commented on submissions/Roophee/friends-app/index.js
> +                        secondFilteredData: []};
change names of this vars to more understandable

2021-02-25 16:26 UTC, babayK0 approved these changes
:+1:

2021-02-25 16:26 UTC, merged