Create FUNDING.yml
kottans/frontend-2021-homeworks pull request #467
Opened 2021-04-04 08:10 UTC by suchov

Think about creating a funding yml

_Have your app published on [GitHub pages](https://github.com/kottans/frontend-2021-homeworks/blob/main/publish-your-app.md). Make sure your PR title contains the task name. Change task name and links below as appropriate. Remove this paragraph._

### task name

[Demo](https://your-username.github.io/app-repo-name)
[Code base](https://github.com/your-username/app-repo-name)

The code is submitted in a dedicated feature branch.
Please, review.

2021-04-04 08:11 UTC, suchov commented on .github/FUNDING.yml
> +github: # [suchov] Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
added my surname just to make the PR valid, we can think about the options that we want to put

2021-04-04 08:12 UTC, suchov commented
Just want to suggest us to think about adding the Funding.yml to our most popular repos...

2021-04-04 09:50 UTC, OleksiyRudenko requested changes
LGTM in general. Just need to finalize the lists.

(Boy, that many funding entry point services around. Of those only heard of github, patreon and [opencollective](https://opencollective.com/pricing))

2021-04-04 09:50 UTC, OleksiyRudenko commented on .github/FUNDING.yml
> +github: # [suchov] Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
```suggestion
github: [suchov] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
```

Uncommented a list of names.

How does a user know if they are sponsors-enabled? Anyway, I think one or two would be sufficient

2021-04-04 09:50 UTC, OleksiyRudenko commented on .github/FUNDING.yml
> +patreon: # Replace with a single Patreon username
```suggestion
patreon: kottans # Replace with a single Patreon username
```

2021-04-06 14:09 UTC, zonzujiro approved these changes

2021-04-10 16:03 UTC, merged