Add html css popup
kottans/frontend-2021-homeworks pull request #49
Opened 2020-10-31 09:45 UTC by VBystrov

Hello!
The code is submitted in a dedicated feature branch.
Please, review.

2020-10-31 10:03 UTC, krylenger commented
it's better to add the direct link to your Demo and code base. 
check out other PR's for an example

2020-10-31 14:34 UTC, VBystrov commented
Here it is:
[demo](https://vbystrov.github.io/html-css-popup/index.html)
[code](https://github.com/VBystrov/html-css-popup)

2020-10-31 16:01 UTC, krylenger commented
Well done! 
A couple of things to improve: 

this is a part of the task: 
_-You'll must able to switch across all interactive elements using only keyboard(without a mouse, don't forget about styles for :focus state)_

It's a good idea to implement this and improve you skill in accessibility.

2020-10-31 16:21 UTC, krylenger commented on submissions/VBystrov/html-css-popup/index.html
> +        <a class="link" href="#">Mail</a>
some unofficial header navigation structure: 
header > ul > li > a

2020-10-31 16:30 UTC, madmaxWMFU requested changes
Good job!
See some comments below

2020-10-31 16:30 UTC, madmaxWMFU commented on submissions/VBystrov/html-css-popup/index.html
> +        <a class="link" href="#">Images</a>
Navigation is best used in this format
```
<nav>
  <ul>
    <li><a href="#">Home</a></li>
    <li><a href="#">About</a></li>
    <li><a href="#">Contact</a></li>
  </ul>
</nav>
```

2020-10-31 16:30 UTC, madmaxWMFU commented on submissions/VBystrov/html-css-popup/index.html
> +      <div class="popup-window" id="popup-window">
The Popup-menu is part of the main menu.

2020-10-31 16:30 UTC, madmaxWMFU commented on submissions/VBystrov/html-css-popup/index.html
> +        <label
This element hasn't focus

2020-10-31 16:30 UTC, madmaxWMFU commented on submissions/VBystrov/html-css-popup/index.html
> +        <label class="popup-more-label" for="popup-more"> MOAR</label>
This element hasn't focus also.

2020-10-31 16:30 UTC, madmaxWMFU commented on submissions/VBystrov/html-css-popup/style.css
> +#popup-checkbox,
Avoid styling by id, better to use the class name

2020-10-31 16:30 UTC, madmaxWMFU commented on submissions/VBystrov/html-css-popup/index.html
> +        <label
Attribute `href` not allowed on the element `label` at this point.

2020-10-31 16:30 UTC, madmaxWMFU commented on submissions/VBystrov/html-css-popup/index.html
> +<html>
Consider adding a `lang` attribute to the `html` start tag to declare the language of this document.

2020-11-03 10:25 UTC, madmaxWMFU approved these changes

2020-11-05 15:48 UTC, merged