HTML-CSS-Popup — #done
kottans/frontend-2021-homeworks pull request #5
Opened 2020-10-15 13:56 UTC by mustbefail

### HTML-CSS-Popup

[Demo](https://mustbefail.github.io/frontend-2021-homeworks/submissions/mustbefail/html-css-popup/) |
[Code base](https://github.com/mustbefail/frontend-2021-homeworks/tree/html-css-popup/submissions/mustbefail/html-css-popup)

The code is submitted in a dedicated feature branch.
Please, review.

2020-10-15 14:15 UTC, AMashoshyna commented
Hi! Great job!

But you accidentally removed example files under `/ submissions/amashoshyna/`. Please restore them. You can do it, for example, by checking out the files from master branch (`git checkout  submissions/amashoshyna`) and commiting them

2020-10-15 14:39 UTC, miroslav-kolomiets requested changes
Good job! But some minor code style and naming issues detected.

2020-10-15 14:39 UTC, miroslav-kolomiets commented on submissions/mustbefail/html-css-popup/index.html
> +
Unnecessary new lines.

2020-10-15 14:39 UTC, miroslav-kolomiets commented on submissions/mustbefail/html-css-popup/index.html
> +
Unnecessary new lines.

2020-10-15 14:39 UTC, miroslav-kolomiets commented on submissions/mustbefail/html-css-popup/index.html
> +</html>
Add new line.

2020-10-15 14:39 UTC, miroslav-kolomiets commented on submissions/mustbefail/html-css-popup/style.css
> +
Unnecessary new line.

2020-10-15 14:39 UTC, miroslav-kolomiets commented on submissions/mustbefail/html-css-popup/style.css
> +
Unnecessary new line.

2020-10-15 14:39 UTC, miroslav-kolomiets commented on submissions/mustbefail/html-css-popup/style.css
> +
Unnecessary new line.

2020-10-15 14:39 UTC, miroslav-kolomiets commented on submissions/mustbefail/html-css-popup/style.css
> +
Unnecessary new line.

2020-10-15 14:39 UTC, miroslav-kolomiets commented on submissions/mustbefail/html-css-popup/style.css
> +
Unnecessary new line.

2020-10-15 14:39 UTC, miroslav-kolomiets commented on submissions/mustbefail/html-css-popup/style.css
> +}
Add new line.

2020-10-15 14:39 UTC, miroslav-kolomiets commented on submissions/mustbefail/html-css-popup/style.css
> +
Unnecessary new line.

2020-10-15 14:39 UTC, miroslav-kolomiets commented on submissions/mustbefail/html-css-popup/style.css
> +
Unnecessary new line.

2020-10-15 14:39 UTC, miroslav-kolomiets commented on submissions/mustbefail/html-css-popup/style.css
> +#popup2 {
It's better to use some more consistent class names, not popup popup2 popup3....

2020-10-16 09:16 UTC, MaxKalashnyk reviewed
Good job! 👍🏻 
It's not a blocker, but according to the comments of @miroslav-kolomiets about redundant spacings, you can use Prettier for automation formatting of your code.
And one comment about the font-awesome icons. It's not a blocker too. You can add just simple SVG icons for these 3 icons in order not to use the whole library for icons.

2020-10-16 09:23 UTC, MaxKalashnyk approved these changes

2020-10-16 10:02 UTC, miroslav-kolomiets approved these changes

2020-10-16 10:03 UTC, miroslav-kolomiets commented
Good job!

2020-10-16 10:03 UTC, merged