Building a Tiny JS World (pre-OOP) and Object-Oriented JavaScript - done
kottans/frontend-2021-homeworks pull request #54
Opened 2020-11-01 19:31 UTC by evgenii-del

_Complete the form below and remove this line._

### Building a Tiny JS World (pre-OOP) - practice
### Object-Oriented JavaScript - practice

[Demo](http://vigorous-step.surge.sh/) |
[Code base](https://github.com/evgenii-del/frontend-nanodegree-arcade-game)

[Demo](http://careful-bean.surge.sh/) |
[Code base](https://github.com/evgenii-del/a-tiny-JS-world)

The code is submitted in a dedicated feature branch.
Please, review.

2020-11-01 20:13 UTC, madmaxWMFU commented
Why are you add PR which consist of two tasks?

2020-11-01 20:19 UTC, evgenii-del commented
@madmaxWMFU I deleted the second task

2020-11-01 20:29 UTC, madmaxWMFU requested changes

2020-11-01 20:29 UTC, madmaxWMFU commented on submissions/evgenii-del/tiny-js-world/index.js
> +[man, woman, cat, dog].forEach(item => print([item.species, item.name, item.gender, item.legs, item.hands, item.saying].join(';')));
Write a function that returns a string with elements of an object.

2020-11-01 21:44 UTC, madmaxWMFU approved these changes

2020-11-02 10:58 UTC, MaxKalashnyk approved these changes
LGTM!

2020-11-02 10:58 UTC, merged