added my frogger-game version
kottans/frontend-2021-homeworks pull request #66
Opened 2020-11-03 19:23 UTC by 5Mountains

### OOP frogger-game

[Demo](https://5mountains.github.io/frontend-nanodegree-arcade-game/) |
[Code base](https://github.com/5Mountains/frontend-2021-homeworks/tree/frogger-game/submissions/5mountains/frogger-game)

The code is submitted in a dedicated feature branch.
Please, review.

2020-11-03 20:00 UTC, AMashoshyna requested changes
NIce job! Please take a look at some comments I left.

2020-11-03 20:04 UTC, 5Mountains commented on submissions/5mountains/frogger-game/app.js
> +(function generateEnemies(){
I just decided to try it, because for me it is new stuff that I learned from udacity courses. But I car remove, easy)

2020-11-03 20:35 UTC, 5Mountains commented on submissions/5mountains/frogger-game/app.js
> +                if (this.x > 0) this.x -= 100;
small clarification, i should create name for `x, y` steps? Like -  `this.stepX = 100;` and the result will be like `if (this.x > 0) this.x -= this.stepX;` Or for canvas dimensions? :confused:

2020-11-03 20:35 UTC, 5Mountains commented on submissions/5mountains/frogger-game/app.js
> +              player.resetStart();
It's clear

2020-11-03 20:36 UTC, 5Mountains commented on submissions/5mountains/frogger-game/app.js
> +    var allowedKeys = {
Didn't even notice that there was `var` left) I'll fix it.

2020-11-03 22:07 UTC, 5Mountains commented
Be so kind and review the code, I think I fulfilled all the requirements! 🙃

2020-11-12 16:30 UTC, AMashoshyna commented
Sorry for the delayed reply! LGTM.

2020-11-12 16:30 UTC, merged