Popup Stoyanova
kottans/frontend-2021-homeworks pull request #8
Opened 2020-10-18 12:25 UTC by AnnaStoyano

Please, review)

2020-10-18 12:31 UTC, madmaxWMFU commented
You forgot to insert links to the demo version and source code

2020-10-18 12:51 UTC, AnnaStoyano commented
I don`t understand how I should create demo. Should I create new repo with this popup folder and make GitHub page?

2020-10-18 12:57 UTC, madmaxWMFU commented
Yes that's right
Just create a repository for this task make [GitHub pages](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)
And then edit the description by adding two links

2020-10-18 12:58 UTC, AnnaStoyano commented
Thank you)

2020-10-18 13:07 UTC, AnnaStoyano commented
I've changed description) Please, can you review again?

2020-10-18 13:16 UTC, madmaxWMFU requested changes
Good job!
Please, see the comments below.

2020-10-18 13:16 UTC, madmaxWMFU commented on submissions/annStoyano/html-css-popup/index.html
> +                <label class="popup_btn-icon" for='popup-check'></label>
Navigation is best used in this format, the sample from [MDN](https://developer.mozilla.org/uk/docs/Web/HTML/%D0%95%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82/nav)
```
<nav>
  <ul>
    <li><a href="#">Home</a></li>
    <li><a href="#">About</a></li>
    <li><a href="#">Contact</a></li>
  </ul>
</nav>
```

2020-10-18 13:16 UTC, madmaxWMFU commented on submissions/annStoyano/html-css-popup/index.html
> +</html>
Add an empty new line. 
You should always leave a blank line at the end of the file.

2020-10-18 16:17 UTC, madmaxWMFU approved these changes

2020-10-18 16:35 UTC, madmaxWMFU commented on submissions/annStoyano/html-css-popup/index.html
> +                                <a href="#" class="popup-item">
Maybe someone of mentors will advise you here to use this tag (`section`) correctly
I would use the usual `div`

2020-10-18 16:40 UTC, madmaxWMFU commented on submissions/annStoyano/html-css-popup/scss/style.scss
> +}
Don't forget about a new line.

You can also set your text editor for adding a new empty line

2020-10-18 19:14 UTC, madmaxWMFU commented
As for me, you are done with this task.
Wait for changes from mentors.

2020-10-18 19:53 UTC, MaxKalashnyk reviewed
Good job! Approved!

2020-10-18 19:54 UTC, MaxKalashnyk approved these changes

2020-10-18 20:49 UTC, madmaxWMFU commented
Maybe make a merge?

2020-10-18 20:51 UTC, merged

2020-11-09 19:21 UTC, madmaxWMFU commented
Сorrect mistakes from [HTML validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fnazar-cmd.github.io%2Fpopup%2F) and [CSS validator](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fnazar-cmd.github.io%2Fpopup%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=ru)