Hooli-style Popup Task
kottans/frontend-2021-homeworks pull request #83
Opened 2020-11-07 19:30 UTC by nallikaea

### Hooli-style Popup

[Demo](https://nallikaea.github.io/html-css-popup/) |
[Code base](https://github.com/nallikaea/html-css-popup)

The code is submitted in a dedicated feature branch.
Please, review ☺

2020-11-07 21:06 UTC, madmaxWMFU requested changes
Good job!
See some comments below

2020-11-07 21:06 UTC, madmaxWMFU commented on submissions/nallikaea/html-css-popup/css/main.css
> +  display: none;
This elements did not have a focus and did not open by space.
Try `display: none;` instead use:
```
opacity: 0;
position: absolute;

2020-11-07 23:02 UTC, lenadgit commented
According to HTML5 specification single tags should be without slash ("/") in the end. Could you please fix it?

2020-11-08 10:22 UTC, nallikaea commented
I made amendments and changed icons, check my demo, please 🙃

2020-11-08 10:55 UTC, nallikaea commented on submissions/nallikaea/html-css-popup/css/main.css
> +#navigation {
Okay, but why?

2020-11-08 10:58 UTC, nallikaea commented on submissions/nallikaea/html-css-popup/css/main.css
> +  height: 36px;
I fixed hight of icons because I want it be equal size. So I decided to change icons at all.

2020-11-08 12:09 UTC, madmaxWMFU commented
Great, now we can open the menu without a mouse using only the keyboard
But there is no focus on menu buttons, some more changes needed

2020-11-08 18:16 UTC, lenadgit requested changes

2020-11-08 18:16 UTC, lenadgit commented on submissions/nallikaea/html-css-popup/index.html
>        <li id="nav-popup">
The list item can"t include all markup. One item can include only text (or text and picture). Could you please fix it? 
Each item in popup should be the list item. 
Id "nav-popup" should be the menu (with structure  nav > ul > li )

2020-11-10 11:22 UTC, nallikaea commented
Hi. 
I made items in popup as a list items. 
And fixed focus on popup menu buttons.

2020-11-10 21:06 UTC, madmaxWMFU approved these changes

2020-11-11 09:18 UTC, nallikaea commented
Good morning, so will you merge it? :) Or I need something to do more?

2020-11-11 10:06 UTC, merged