initial pop-up commit
kottans/frontend-2021-homeworks pull request #96
Opened 2020-11-09 17:46 UTC by Writerman

_Complete the form below and remove this line._

### task name

[Demo](link-to-webpage-on-github-pages) |
[Code base](link-to-complete-codebase-in-different-repo)

The code is submitted in a dedicated feature branch.
Please, review.

2020-11-09 19:45 UTC, madmaxWMFU commented
Please correct your demo link)

2020-11-10 12:28 UTC, Writerman commented
Did I do it right?

2020-11-11 09:53 UTC, madmaxWMFU commented on submissions/Writerman/my_pop_up/index.html
> +    <main class="main">
Tag `main` should situated in `body`. 
The tag main is unclosed.

2020-11-11 10:28 UTC, madmaxWMFU requested changes
Good job, see some comments below

2020-11-11 10:28 UTC, madmaxWMFU commented on submissions/Writerman/my_pop_up/index.html
> +                <label
Add a focus for this element

2020-11-11 10:28 UTC, madmaxWMFU commented on submissions/Writerman/my_pop_up/index.html
> +        <div class="pop_up">
Make sure the links doesn't overlap with menu.

2020-11-11 15:55 UTC, Writerman commented
I fix it.

2020-11-12 21:37 UTC, madmaxWMFU commented
Tag `main` must be under tag `nav`.

2020-11-12 21:37 UTC, madmaxWMFU approved these changes

2020-11-13 22:12 UTC, miroslav-kolomiets requested changes
Nice job! But something can be improved.
<img width="747" alt="Снимок экрана 2020-11-14 в 12 11 45 AM" src="https://user-images.githubusercontent.com/14906260/99126062-19d94880-260e-11eb-94d1-40811ef7d120.png">

2020-11-13 22:12 UTC, miroslav-kolomiets commented on submissions/Writerman/my_pop_up/css/style.css
> +  border: 2px solid #666666;
```suggestion
  border: 2px solid #666;
```
If you use in other places short syntax, use it everywhere ;)

2020-11-13 22:12 UTC, miroslav-kolomiets commented on submissions/Writerman/my_pop_up/css/style.css
> +{
```suggestion
.icon_defend {
```

2020-11-13 22:12 UTC, miroslav-kolomiets commented on submissions/Writerman/my_pop_up/css/style.css
> +.icon_User {
```suggestion
.icon_user {
```

2020-11-13 22:12 UTC, miroslav-kolomiets commented on submissions/Writerman/my_pop_up/css/style.css
> +.icon_Atack {
```suggestion
.icon_atack {
```

2020-11-16 20:26 UTC, miroslav-kolomiets commented
Hi! @Writerman, do you need any help with this?

2020-11-17 14:37 UTC, Writerman commented
I've fixed it.

2020-11-18 20:52 UTC, A-Ostrovnyy commented on submissions/Writerman/my_pop_up/css/style.css
> +.toggle_input {
Watch the [video](https://www.youtube.com/watch?v=E6kLaaQFctU&t=413s) about hiding checkboxes in the right way

2020-11-18 20:54 UTC, A-Ostrovnyy commented on submissions/Writerman/my_pop_up/css/style.css
> +    background: #fff;
Use [Prettier](https://prettier.io/) for formatting your code.

2020-11-18 20:55 UTC, A-Ostrovnyy requested changes
Nice work!
See my comment above!

2020-11-18 21:09 UTC, miroslav-kolomiets requested changes
NIce job. But something still needs to be done.

2020-11-18 21:09 UTC, miroslav-kolomiets commented on submissions/Writerman/my_pop_up/css/style.css
> +.icon_first {
This is also bad practice. Here and below. Better to name the icons essentially. Describing what the icon actually is.

2021-01-02 09:18 UTC, OleksiyRudenko commented
Closing this PR for a long time inactivity.
@Writerman  please feel free reopening this PR once you have updates based on reviewers' comments.

2021-01-02 09:18 UTC, closed without merging